-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity k2c_dense_2_denseAem_rom is 
    generic(
             DWIDTH     : integer := 32; 
             AWIDTH     : integer := 5; 
             MEM_SIZE    : integer := 25
    ); 
    port (
          addr0      : in std_logic_vector(AWIDTH-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(DWIDTH-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of k2c_dense_2_denseAem_rom is 

signal addr0_tmp : std_logic_vector(AWIDTH-1 downto 0); 
type mem_array is array (0 to MEM_SIZE-1) of std_logic_vector (DWIDTH-1 downto 0); 
signal mem : mem_array := (
    0 => "10111011110110111111110111000001", 
    1 => "00111011110001110101000111000111", 
    2 => "10111100111101110010111101101100", 
    3 => "10111100110111111100100001111011", 
    4 => "10111100001100001110101100110001", 
    5 => "00111101111001011010001110000111", 
    6 => "00111101111101101010101001001000", 
    7 => "00111101001000000101101100110000", 
    8 => "10111100111111000110100011011010", 
    9 => "00111110000100000011110100100101", 
    10 => "10111011001110000111100110101100", 
    11 => "00111101110010010010110111000001", 
    12 => "10111101000001111001010100101000", 
    13 => "00111101111101010011001101001000", 
    14 => "00111101011101001110100100001000", 
    15 => "00111101101011001110000010111010", 
    16 => "00111110000001100011000111100001", 
    17 => "10111100100110000010100111011001", 
    18 => "10111101011101010000001001100100", 
    19 => "00111101010101011011110110100110", 
    20 => "00111011000101110111000000110111", 
    21 => "00111101110111100100110000001111", 
    22 => "00111110001000010001010011110000", 
    23 => "00111101110100000000111110110101", 
    24 => "10111100011011111010111110000000" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity k2c_dense_2_denseAem is
    generic (
        DataWidth : INTEGER := 32;
        AddressRange : INTEGER := 25;
        AddressWidth : INTEGER := 5);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of k2c_dense_2_denseAem is
    component k2c_dense_2_denseAem_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    k2c_dense_2_denseAem_rom_U :  component k2c_dense_2_denseAem_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


