// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        p_read35,
        p_read36,
        p_read37,
        p_read38,
        p_read39,
        p_read40,
        p_read41,
        p_read42,
        p_read43,
        p_read44,
        p_read45,
        p_read46,
        p_read47,
        p_read48,
        p_read49,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
input  [15:0] p_read9;
input  [15:0] p_read10;
input  [15:0] p_read11;
input  [15:0] p_read12;
input  [15:0] p_read13;
input  [15:0] p_read14;
input  [15:0] p_read15;
input  [15:0] p_read16;
input  [15:0] p_read17;
input  [15:0] p_read18;
input  [15:0] p_read19;
input  [15:0] p_read20;
input  [15:0] p_read21;
input  [15:0] p_read22;
input  [15:0] p_read23;
input  [15:0] p_read24;
input  [15:0] p_read25;
input  [15:0] p_read26;
input  [15:0] p_read27;
input  [15:0] p_read28;
input  [15:0] p_read29;
input  [15:0] p_read30;
input  [15:0] p_read31;
input  [15:0] p_read32;
input  [15:0] p_read33;
input  [15:0] p_read34;
input  [15:0] p_read35;
input  [15:0] p_read36;
input  [15:0] p_read37;
input  [15:0] p_read38;
input  [15:0] p_read39;
input  [15:0] p_read40;
input  [15:0] p_read41;
input  [15:0] p_read42;
input  [15:0] p_read43;
input  [15:0] p_read44;
input  [15:0] p_read45;
input  [15:0] p_read46;
input  [15:0] p_read47;
input  [15:0] p_read48;
input  [15:0] p_read49;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [10:0] w6_V_address0;
reg    w6_V_ce0;
wire   [10:0] w6_V_q0;
wire   [10:0] next_mul_fu_6073_p2;
reg   [10:0] next_mul_reg_7486;
wire    ap_CS_fsm_state2;
wire   [5:0] ii_3_fu_6085_p2;
reg   [5:0] ii_3_reg_7494;
wire  signed [25:0] OP1_V_cast_fu_6147_p1;
reg  signed [25:0] OP1_V_cast_reg_7499;
wire   [0:0] tmp_fu_6079_p2;
wire   [4:0] jj_3_fu_6161_p2;
reg   [4:0] jj_3_reg_7657;
wire    ap_CS_fsm_state3;
wire   [63:0] tmp_14_fu_6173_p1;
reg   [63:0] tmp_14_reg_7662;
wire   [0:0] tmp_13_fu_6155_p2;
reg   [15:0] tmp_17_reg_7672;
wire    ap_CS_fsm_state4;
wire   [4:0] iacc_2_fu_6274_p2;
reg   [4:0] iacc_2_reg_7680;
wire    ap_CS_fsm_state6;
wire   [10:0] next_mul2_fu_6586_p2;
reg   [10:0] next_mul2_reg_7860;
wire    ap_CS_fsm_state8;
wire   [5:0] ii_4_fu_6598_p2;
reg   [5:0] ii_4_reg_7868;
wire   [4:0] jj_4_fu_6614_p2;
reg   [4:0] jj_4_reg_8026;
wire    ap_CS_fsm_state9;
wire   [0:0] tmp_21_fu_6608_p2;
wire   [4:0] ires_2_fu_6824_p2;
reg   [4:0] ires_2_reg_8039;
wire    ap_CS_fsm_state11;
reg   [10:0] mult_V_address0;
reg    mult_V_ce0;
reg    mult_V_we0;
wire   [15:0] mult_V_q0;
reg   [5:0] ii_reg_900;
reg   [10:0] phi_mul_reg_911;
reg   [4:0] jj_reg_923;
wire    ap_CS_fsm_state5;
wire   [4:0] ap_phi_mux_iacc_phi_fu_938_p4;
reg   [4:0] iacc_reg_934;
wire    ap_CS_fsm_state7;
reg   [5:0] ii2_reg_945;
wire   [0:0] tmp_s_fu_6268_p2;
reg   [10:0] phi_mul1_reg_956;
reg   [4:0] jj3_reg_968;
wire   [0:0] tmp_16_fu_6592_p2;
wire    ap_CS_fsm_state10;
wire   [4:0] ap_phi_mux_ires_phi_fu_984_p4;
reg   [4:0] ires_reg_980;
wire    ap_CS_fsm_state12;
wire   [63:0] tmp_22_fu_6626_p1;
reg   [15:0] acc_24_V_1_fu_268;
wire   [15:0] acc_0_V_fu_6280_p27;
reg   [15:0] acc_24_V_3_fu_272;
reg   [15:0] acc_24_V_4_fu_276;
reg   [15:0] acc_24_V_5_fu_280;
reg   [15:0] acc_24_V_6_fu_284;
reg   [15:0] acc_24_V_7_fu_288;
reg   [15:0] acc_24_V_8_fu_292;
reg   [15:0] acc_24_V_9_fu_296;
reg   [15:0] acc_24_V_10_fu_300;
reg   [15:0] acc_24_V_11_fu_304;
reg   [15:0] acc_24_V_12_fu_308;
reg   [15:0] acc_24_V_13_fu_312;
reg   [15:0] acc_24_V_14_fu_316;
reg   [15:0] acc_24_V_15_fu_320;
reg   [15:0] acc_24_V_16_fu_324;
reg   [15:0] acc_24_V_17_fu_328;
reg   [15:0] acc_24_V_18_fu_332;
reg   [15:0] acc_24_V_19_fu_336;
reg   [15:0] acc_24_V_20_fu_340;
reg   [15:0] acc_24_V_21_fu_344;
reg   [15:0] acc_24_V_22_fu_348;
reg   [15:0] acc_24_V_23_fu_352;
reg   [15:0] acc_24_V_24_fu_356;
reg   [15:0] acc_24_V_25_fu_360;
reg   [15:0] acc_24_V_fu_364;
reg   [15:0] acc_24_V_26_fu_368;
wire   [15:0] acc_0_V_4_fu_6687_p2;
wire   [0:0] tmp_19_fu_6818_p2;
reg   [15:0] acc_24_V_27_fu_372;
reg   [15:0] acc_24_V_28_fu_376;
reg   [15:0] acc_24_V_29_fu_380;
reg   [15:0] acc_24_V_30_fu_384;
reg   [15:0] acc_24_V_31_fu_388;
reg   [15:0] acc_24_V_32_fu_392;
reg   [15:0] acc_24_V_33_fu_396;
reg   [15:0] acc_24_V_34_fu_400;
reg   [15:0] acc_24_V_35_fu_404;
reg   [15:0] acc_24_V_36_fu_408;
reg   [15:0] acc_24_V_37_fu_412;
reg   [15:0] acc_24_V_38_fu_416;
reg   [15:0] acc_24_V_39_fu_420;
reg   [15:0] acc_24_V_40_fu_424;
reg   [15:0] acc_24_V_41_fu_428;
reg   [15:0] acc_24_V_42_fu_432;
reg   [15:0] acc_24_V_43_fu_436;
reg   [15:0] acc_24_V_44_fu_440;
reg   [15:0] acc_24_V_45_fu_444;
reg   [15:0] acc_24_V_46_fu_448;
reg   [15:0] acc_24_V_47_fu_452;
reg   [15:0] acc_24_V_48_fu_456;
reg   [15:0] acc_24_V_49_fu_460;
reg   [15:0] acc_24_V_2_fu_464;
reg   [15:0] res_24_V_write_assign_fu_468;
wire   [15:0] tmp_48_fu_6830_p27;
reg   [15:0] res_23_V_write_assign_fu_472;
reg   [15:0] res_0_V_write_assign_fu_476;
reg   [15:0] res_22_V_write_assign_fu_480;
reg   [15:0] res_21_V_write_assign_fu_484;
reg   [15:0] res_1_V_write_assign_fu_488;
reg   [15:0] res_20_V_write_assign_fu_492;
reg   [15:0] res_19_V_write_assign_fu_496;
reg   [15:0] res_2_V_write_assign_fu_500;
reg   [15:0] res_18_V_write_assign_fu_504;
reg   [15:0] res_17_V_write_assign_fu_508;
reg   [15:0] res_3_V_write_assign_fu_512;
reg   [15:0] res_16_V_write_assign_fu_516;
reg   [15:0] res_15_V_write_assign_fu_520;
reg   [15:0] res_4_V_write_assign_fu_524;
reg   [15:0] res_14_V_write_assign_fu_528;
reg   [15:0] res_13_V_write_assign_fu_532;
reg   [15:0] res_5_V_write_assign_fu_536;
reg   [15:0] res_12_V_write_assign_fu_540;
reg   [15:0] res_11_V_write_assign_fu_544;
reg   [15:0] res_6_V_write_assign_fu_548;
reg   [15:0] res_10_V_write_assign_fu_552;
reg   [15:0] res_9_V_write_assign_fu_556;
reg   [15:0] res_7_V_write_assign_fu_560;
reg   [15:0] res_8_V_write_assign_fu_564;
wire  signed [15:0] p_Val2_s_fu_2121_p0;
wire  signed [10:0] p_Val2_s_fu_2121_p1;
wire   [15:0] cache_V_fu_6091_p52;
wire   [10:0] jj_cast_fu_6151_p1;
wire   [10:0] index_fu_6167_p2;
wire   [25:0] p_Val2_s_fu_2121_p2;
wire   [10:0] jj3_cast_fu_6604_p1;
wire   [10:0] index_2_fu_6620_p2;
wire   [15:0] p_Val2_43_fu_6631_p27;
reg   [11:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
end

dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_w6_V #(
    .DataWidth( 11 ),
    .AddressRange( 1250 ),
    .AddressWidth( 11 ))
w6_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w6_V_address0),
    .ce0(w6_V_ce0),
    .q0(w6_V_q0)
);

dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_mult_V #(
    .DataWidth( 16 ),
    .AddressRange( 1250 ),
    .AddressWidth( 11 ))
mult_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mult_V_address0),
    .ce0(mult_V_ce0),
    .we0(mult_V_we0),
    .d0(tmp_17_reg_7672),
    .q0(mult_V_q0)
);

myproject_mux_506_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 16 ),
    .din26_WIDTH( 16 ),
    .din27_WIDTH( 16 ),
    .din28_WIDTH( 16 ),
    .din29_WIDTH( 16 ),
    .din30_WIDTH( 16 ),
    .din31_WIDTH( 16 ),
    .din32_WIDTH( 16 ),
    .din33_WIDTH( 16 ),
    .din34_WIDTH( 16 ),
    .din35_WIDTH( 16 ),
    .din36_WIDTH( 16 ),
    .din37_WIDTH( 16 ),
    .din38_WIDTH( 16 ),
    .din39_WIDTH( 16 ),
    .din40_WIDTH( 16 ),
    .din41_WIDTH( 16 ),
    .din42_WIDTH( 16 ),
    .din43_WIDTH( 16 ),
    .din44_WIDTH( 16 ),
    .din45_WIDTH( 16 ),
    .din46_WIDTH( 16 ),
    .din47_WIDTH( 16 ),
    .din48_WIDTH( 16 ),
    .din49_WIDTH( 16 ),
    .din50_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
myproject_mux_506_16_1_1_U267(
    .din0(p_read),
    .din1(p_read1),
    .din2(p_read2),
    .din3(p_read3),
    .din4(p_read4),
    .din5(p_read5),
    .din6(p_read6),
    .din7(p_read7),
    .din8(p_read8),
    .din9(p_read9),
    .din10(p_read10),
    .din11(p_read11),
    .din12(p_read12),
    .din13(p_read13),
    .din14(p_read14),
    .din15(p_read15),
    .din16(p_read16),
    .din17(p_read17),
    .din18(p_read18),
    .din19(p_read19),
    .din20(p_read20),
    .din21(p_read21),
    .din22(p_read22),
    .din23(p_read23),
    .din24(p_read24),
    .din25(p_read25),
    .din26(p_read26),
    .din27(p_read27),
    .din28(p_read28),
    .din29(p_read29),
    .din30(p_read30),
    .din31(p_read31),
    .din32(p_read32),
    .din33(p_read33),
    .din34(p_read34),
    .din35(p_read35),
    .din36(p_read36),
    .din37(p_read37),
    .din38(p_read38),
    .din39(p_read39),
    .din40(p_read40),
    .din41(p_read41),
    .din42(p_read42),
    .din43(p_read43),
    .din44(p_read44),
    .din45(p_read45),
    .din46(p_read46),
    .din47(p_read47),
    .din48(p_read48),
    .din49(p_read49),
    .din50(ii_reg_900),
    .dout(cache_V_fu_6091_p52)
);

myproject_mux_255_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 5 ),
    .dout_WIDTH( 16 ))
myproject_mux_255_16_1_1_U268(
    .din0(16'd65529),
    .din1(16'd6),
    .din2(16'd65505),
    .din3(16'd65508),
    .din4(16'd65524),
    .din5(16'd114),
    .din6(16'd123),
    .din7(16'd40),
    .din8(16'd65504),
    .din9(16'd144),
    .din10(16'd65533),
    .din11(16'd100),
    .din12(16'd65502),
    .din13(16'd122),
    .din14(16'd61),
    .din15(16'd86),
    .din16(16'd134),
    .din17(16'd65516),
    .din18(16'd65474),
    .din19(16'd53),
    .din20(16'd2),
    .din21(16'd111),
    .din22(16'd161),
    .din23(16'd104),
    .din24(16'd65521),
    .din25(iacc_reg_934),
    .dout(acc_0_V_fu_6280_p27)
);

myproject_mux_255_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 5 ),
    .dout_WIDTH( 16 ))
myproject_mux_255_16_1_1_U269(
    .din0(acc_24_V_26_fu_368),
    .din1(acc_24_V_27_fu_372),
    .din2(acc_24_V_28_fu_376),
    .din3(acc_24_V_29_fu_380),
    .din4(acc_24_V_30_fu_384),
    .din5(acc_24_V_31_fu_388),
    .din6(acc_24_V_32_fu_392),
    .din7(acc_24_V_33_fu_396),
    .din8(acc_24_V_34_fu_400),
    .din9(acc_24_V_35_fu_404),
    .din10(acc_24_V_36_fu_408),
    .din11(acc_24_V_37_fu_412),
    .din12(acc_24_V_38_fu_416),
    .din13(acc_24_V_39_fu_420),
    .din14(acc_24_V_40_fu_424),
    .din15(acc_24_V_41_fu_428),
    .din16(acc_24_V_42_fu_432),
    .din17(acc_24_V_43_fu_436),
    .din18(acc_24_V_44_fu_440),
    .din19(acc_24_V_45_fu_444),
    .din20(acc_24_V_46_fu_448),
    .din21(acc_24_V_47_fu_452),
    .din22(acc_24_V_48_fu_456),
    .din23(acc_24_V_49_fu_460),
    .din24(acc_24_V_2_fu_464),
    .din25(jj3_reg_968),
    .dout(p_Val2_43_fu_6631_p27)
);

myproject_mux_255_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 16 ),
    .din17_WIDTH( 16 ),
    .din18_WIDTH( 16 ),
    .din19_WIDTH( 16 ),
    .din20_WIDTH( 16 ),
    .din21_WIDTH( 16 ),
    .din22_WIDTH( 16 ),
    .din23_WIDTH( 16 ),
    .din24_WIDTH( 16 ),
    .din25_WIDTH( 5 ),
    .dout_WIDTH( 16 ))
myproject_mux_255_16_1_1_U270(
    .din0(acc_24_V_26_fu_368),
    .din1(acc_24_V_27_fu_372),
    .din2(acc_24_V_28_fu_376),
    .din3(acc_24_V_29_fu_380),
    .din4(acc_24_V_30_fu_384),
    .din5(acc_24_V_31_fu_388),
    .din6(acc_24_V_32_fu_392),
    .din7(acc_24_V_33_fu_396),
    .din8(acc_24_V_34_fu_400),
    .din9(acc_24_V_35_fu_404),
    .din10(acc_24_V_36_fu_408),
    .din11(acc_24_V_37_fu_412),
    .din12(acc_24_V_38_fu_416),
    .din13(acc_24_V_39_fu_420),
    .din14(acc_24_V_40_fu_424),
    .din15(acc_24_V_41_fu_428),
    .din16(acc_24_V_42_fu_432),
    .din17(acc_24_V_43_fu_436),
    .din18(acc_24_V_44_fu_440),
    .din19(acc_24_V_45_fu_444),
    .din20(acc_24_V_46_fu_448),
    .din21(acc_24_V_47_fu_452),
    .din22(acc_24_V_48_fu_456),
    .din23(acc_24_V_49_fu_460),
    .din24(acc_24_V_2_fu_464),
    .din25(ires_reg_980),
    .dout(tmp_48_fu_6830_p27)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd0) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_26_fu_368 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_26_fu_368 <= acc_24_V_1_fu_268;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_27_fu_372 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_27_fu_372 <= acc_24_V_3_fu_272;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd2) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_28_fu_376 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_28_fu_376 <= acc_24_V_4_fu_276;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd3) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_29_fu_380 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_29_fu_380 <= acc_24_V_5_fu_280;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & ((jj3_reg_968 == 5'd31) | (jj3_reg_968 == 5'd30) | (jj3_reg_968 == 5'd29) | (jj3_reg_968 == 5'd28) | (jj3_reg_968 == 5'd27) | (jj3_reg_968 == 5'd26) | (jj3_reg_968 == 5'd25) | (jj3_reg_968 == 5'd24)))) begin
        acc_24_V_2_fu_464 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_2_fu_464 <= acc_24_V_fu_364;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd4) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_30_fu_384 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_30_fu_384 <= acc_24_V_6_fu_284;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd5) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_31_fu_388 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_31_fu_388 <= acc_24_V_7_fu_288;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd6) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_32_fu_392 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_32_fu_392 <= acc_24_V_8_fu_292;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd7) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_33_fu_396 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_33_fu_396 <= acc_24_V_9_fu_296;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd8) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_34_fu_400 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_34_fu_400 <= acc_24_V_10_fu_300;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd9) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_35_fu_404 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_35_fu_404 <= acc_24_V_11_fu_304;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd10) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_36_fu_408 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_36_fu_408 <= acc_24_V_12_fu_308;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd11) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_37_fu_412 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_37_fu_412 <= acc_24_V_13_fu_312;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd12) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_38_fu_416 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_38_fu_416 <= acc_24_V_14_fu_316;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd13) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_39_fu_420 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_39_fu_420 <= acc_24_V_15_fu_320;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd14) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_40_fu_424 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_40_fu_424 <= acc_24_V_16_fu_324;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd15) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_41_fu_428 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_41_fu_428 <= acc_24_V_17_fu_328;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd16) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_42_fu_432 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_42_fu_432 <= acc_24_V_18_fu_332;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd17) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_43_fu_436 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_43_fu_436 <= acc_24_V_19_fu_336;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd18) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_44_fu_440 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_44_fu_440 <= acc_24_V_20_fu_340;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd19) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_45_fu_444 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_45_fu_444 <= acc_24_V_21_fu_344;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd20) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_46_fu_448 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_46_fu_448 <= acc_24_V_22_fu_348;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd21) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_47_fu_452 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_47_fu_452 <= acc_24_V_23_fu_352;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd22) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_48_fu_456 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_48_fu_456 <= acc_24_V_24_fu_356;
    end
end

always @ (posedge ap_clk) begin
    if (((jj3_reg_968 == 5'd23) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_24_V_49_fu_460 <= acc_0_V_4_fu_6687_p2;
    end else if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_49_fu_460 <= acc_24_V_25_fu_360;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        iacc_reg_934 <= iacc_2_reg_7680;
    end else if (((tmp_fu_6079_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        iacc_reg_934 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        ii2_reg_945 <= 6'd0;
    end else if (((tmp_21_fu_6608_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        ii2_reg_945 <= ii_4_reg_7868;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_13_fu_6155_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ii_reg_900 <= ii_3_reg_7494;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        ii_reg_900 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ires_reg_980 <= ires_2_reg_8039;
    end else if (((tmp_16_fu_6592_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        ires_reg_980 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        jj3_reg_968 <= jj_4_reg_8026;
    end else if (((tmp_16_fu_6592_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        jj3_reg_968 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        jj_reg_923 <= jj_3_reg_7657;
    end else if (((tmp_fu_6079_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        jj_reg_923 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        phi_mul1_reg_956 <= 11'd0;
    end else if (((tmp_21_fu_6608_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        phi_mul1_reg_956 <= next_mul2_reg_7860;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_13_fu_6155_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        phi_mul_reg_911 <= next_mul_reg_7486;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_mul_reg_911 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_6079_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        OP1_V_cast_reg_7499 <= OP1_V_cast_fu_6147_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd8) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_10_fu_300 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd9) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_11_fu_304 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd10) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_12_fu_308 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd11) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_13_fu_312 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd12) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_14_fu_316 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd13) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_15_fu_320 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd14) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_16_fu_324 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd15) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_17_fu_328 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd16) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_18_fu_332 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd17) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_19_fu_336 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd0) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_1_fu_268 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd18) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_20_fu_340 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd19) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_21_fu_344 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd20) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_22_fu_348 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd21) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_23_fu_352 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd22) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_24_fu_356 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd23) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_25_fu_360 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd1) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_3_fu_272 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd2) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_4_fu_276 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd3) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_5_fu_280 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd4) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_6_fu_284 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd5) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_7_fu_288 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd6) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_8_fu_292 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd7) & (tmp_s_fu_6268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_24_V_9_fu_296 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd31) & (tmp_s_fu_6268_p2 == 1'd0)) | ((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd30) & (tmp_s_fu_6268_p2 == 1'd0)) | ((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd29) & (tmp_s_fu_6268_p2 == 1'd0)) | ((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd28) & (tmp_s_fu_6268_p2 == 1'd0)) | ((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd27) & (tmp_s_fu_6268_p2 == 1'd0)) | ((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd26) & (tmp_s_fu_6268_p2 == 1'd0)) | ((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd25) & (tmp_s_fu_6268_p2 == 1'd0)) | ((ap_phi_mux_iacc_phi_fu_938_p4 == 5'd24) & (tmp_s_fu_6268_p2 == 1'd0))))) begin
        acc_24_V_fu_364 <= acc_0_V_fu_6280_p27;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        iacc_2_reg_7680 <= iacc_2_fu_6274_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ii_3_reg_7494 <= ii_3_fu_6085_p2;
        next_mul_reg_7486 <= next_mul_fu_6073_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ii_4_reg_7868 <= ii_4_fu_6598_p2;
        next_mul2_reg_7860 <= next_mul2_fu_6586_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ires_2_reg_8039 <= ires_2_fu_6824_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        jj_3_reg_7657 <= jj_3_fu_6161_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        jj_4_reg_8026 <= jj_4_fu_6614_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd0) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_0_V_write_assign_fu_476 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd10) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_10_V_write_assign_fu_552 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd11) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_11_V_write_assign_fu_544 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd12) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_12_V_write_assign_fu_540 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd13) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_13_V_write_assign_fu_532 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd14) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_14_V_write_assign_fu_528 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd15) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_15_V_write_assign_fu_520 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd16) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_16_V_write_assign_fu_516 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd17) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_17_V_write_assign_fu_508 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd18) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_18_V_write_assign_fu_504 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd19) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_19_V_write_assign_fu_496 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd1) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_1_V_write_assign_fu_488 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd20) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_20_V_write_assign_fu_492 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd21) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_21_V_write_assign_fu_484 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd22) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_22_V_write_assign_fu_480 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd23) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_23_V_write_assign_fu_472 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) & (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd31) & (tmp_19_fu_6818_p2 == 1'd0)) | ((ap_phi_mux_ires_phi_fu_984_p4 == 5'd30) & (tmp_19_fu_6818_p2 == 1'd0)) | ((ap_phi_mux_ires_phi_fu_984_p4 == 5'd29) & (tmp_19_fu_6818_p2 == 1'd0)) | ((ap_phi_mux_ires_phi_fu_984_p4 == 5'd28) & (tmp_19_fu_6818_p2 == 1'd0)) | ((ap_phi_mux_ires_phi_fu_984_p4 == 5'd27) & (tmp_19_fu_6818_p2 == 1'd0)) | ((ap_phi_mux_ires_phi_fu_984_p4 == 5'd26) & (tmp_19_fu_6818_p2 == 1'd0)) | ((ap_phi_mux_ires_phi_fu_984_p4 == 5'd25) & (tmp_19_fu_6818_p2 == 1'd0)) | ((ap_phi_mux_ires_phi_fu_984_p4 == 5'd24) & (tmp_19_fu_6818_p2 == 1'd0))))) begin
        res_24_V_write_assign_fu_468 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd2) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_2_V_write_assign_fu_500 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd3) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_3_V_write_assign_fu_512 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd4) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_4_V_write_assign_fu_524 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd5) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_5_V_write_assign_fu_536 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd6) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_6_V_write_assign_fu_548 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd7) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_7_V_write_assign_fu_560 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd8) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_8_V_write_assign_fu_564 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_ires_phi_fu_984_p4 == 5'd9) & (tmp_19_fu_6818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        res_9_V_write_assign_fu_556 <= tmp_48_fu_6830_p27;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_13_fu_6155_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_14_reg_7662[10 : 0] <= tmp_14_fu_6173_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_17_reg_7672 <= {{p_Val2_s_fu_2121_p2[25:10]}};
    end
end

always @ (*) begin
    if ((((tmp_19_fu_6818_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_19_fu_6818_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        mult_V_address0 = tmp_22_fu_6626_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mult_V_address0 = tmp_14_reg_7662;
    end else begin
        mult_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state9))) begin
        mult_V_ce0 = 1'b1;
    end else begin
        mult_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mult_V_we0 = 1'b1;
    end else begin
        mult_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        w6_V_ce0 = 1'b1;
    end else begin
        w6_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_fu_6079_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((tmp_13_fu_6155_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state6 : begin
            if (((tmp_s_fu_6268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state8 : begin
            if (((tmp_16_fu_6592_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((tmp_21_fu_6608_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state11 : begin
            if (((tmp_19_fu_6818_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OP1_V_cast_fu_6147_p1 = $signed(cache_V_fu_6091_p52);

assign acc_0_V_4_fu_6687_p2 = (mult_V_q0 + p_Val2_43_fu_6631_p27);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_phi_mux_iacc_phi_fu_938_p4 = iacc_reg_934;

assign ap_phi_mux_ires_phi_fu_984_p4 = ires_reg_980;

assign ap_return_0 = res_0_V_write_assign_fu_476;

assign ap_return_1 = res_1_V_write_assign_fu_488;

assign ap_return_10 = res_10_V_write_assign_fu_552;

assign ap_return_11 = res_11_V_write_assign_fu_544;

assign ap_return_12 = res_12_V_write_assign_fu_540;

assign ap_return_13 = res_13_V_write_assign_fu_532;

assign ap_return_14 = res_14_V_write_assign_fu_528;

assign ap_return_15 = res_15_V_write_assign_fu_520;

assign ap_return_16 = res_16_V_write_assign_fu_516;

assign ap_return_17 = res_17_V_write_assign_fu_508;

assign ap_return_18 = res_18_V_write_assign_fu_504;

assign ap_return_19 = res_19_V_write_assign_fu_496;

assign ap_return_2 = res_2_V_write_assign_fu_500;

assign ap_return_20 = res_20_V_write_assign_fu_492;

assign ap_return_21 = res_21_V_write_assign_fu_484;

assign ap_return_22 = res_22_V_write_assign_fu_480;

assign ap_return_23 = res_23_V_write_assign_fu_472;

assign ap_return_24 = res_24_V_write_assign_fu_468;

assign ap_return_3 = res_3_V_write_assign_fu_512;

assign ap_return_4 = res_4_V_write_assign_fu_524;

assign ap_return_5 = res_5_V_write_assign_fu_536;

assign ap_return_6 = res_6_V_write_assign_fu_548;

assign ap_return_7 = res_7_V_write_assign_fu_560;

assign ap_return_8 = res_8_V_write_assign_fu_564;

assign ap_return_9 = res_9_V_write_assign_fu_556;

assign iacc_2_fu_6274_p2 = (iacc_reg_934 + 5'd1);

assign ii_3_fu_6085_p2 = (ii_reg_900 + 6'd1);

assign ii_4_fu_6598_p2 = (ii2_reg_945 + 6'd1);

assign index_2_fu_6620_p2 = (phi_mul1_reg_956 + jj3_cast_fu_6604_p1);

assign index_fu_6167_p2 = (phi_mul_reg_911 + jj_cast_fu_6151_p1);

assign ires_2_fu_6824_p2 = (ires_reg_980 + 5'd1);

assign jj3_cast_fu_6604_p1 = jj3_reg_968;

assign jj_3_fu_6161_p2 = (jj_reg_923 + 5'd1);

assign jj_4_fu_6614_p2 = (jj3_reg_968 + 5'd1);

assign jj_cast_fu_6151_p1 = jj_reg_923;

assign next_mul2_fu_6586_p2 = (phi_mul1_reg_956 + 11'd25);

assign next_mul_fu_6073_p2 = (phi_mul_reg_911 + 11'd25);

assign p_Val2_s_fu_2121_p0 = OP1_V_cast_reg_7499;

assign p_Val2_s_fu_2121_p1 = w6_V_q0;

assign p_Val2_s_fu_2121_p2 = ($signed(p_Val2_s_fu_2121_p0) * $signed(p_Val2_s_fu_2121_p1));

assign tmp_13_fu_6155_p2 = ((jj_reg_923 == 5'd25) ? 1'b1 : 1'b0);

assign tmp_14_fu_6173_p1 = index_fu_6167_p2;

assign tmp_16_fu_6592_p2 = ((ii2_reg_945 == 6'd50) ? 1'b1 : 1'b0);

assign tmp_19_fu_6818_p2 = ((ires_reg_980 == 5'd25) ? 1'b1 : 1'b0);

assign tmp_21_fu_6608_p2 = ((jj3_reg_968 == 5'd25) ? 1'b1 : 1'b0);

assign tmp_22_fu_6626_p1 = index_2_fu_6620_p2;

assign tmp_fu_6079_p2 = ((ii_reg_900 == 6'd50) ? 1'b1 : 1'b0);

assign tmp_s_fu_6268_p2 = ((iacc_reg_934 == 5'd25) ? 1'b1 : 1'b0);

assign w6_V_address0 = tmp_14_fu_6173_p1;

always @ (posedge ap_clk) begin
    tmp_14_reg_7662[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
end

endmodule //dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0
