-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config9_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_8_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config9_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_1FF : STD_LOGIC_VECTOR (9 downto 0) := "0111111111";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv18_1FFFF : STD_LOGIC_VECTOR (17 downto 0) := "011111111111111111";
    constant ap_const_lv18_20000 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_state6_pp0_stage2_iter1 : BOOLEAN;
    signal ap_block_state9_pp0_stage2_iter2 : BOOLEAN;
    signal ap_block_state12_pp0_stage2_iter3 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal exp_table1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce0 : STD_LOGIC;
    signal exp_table1_q0 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce1 : STD_LOGIC;
    signal exp_table1_q1 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table1_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce2 : STD_LOGIC;
    signal exp_table1_q2 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_table1_address3 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce3 : STD_LOGIC;
    signal exp_table1_q3 : STD_LOGIC_VECTOR (16 downto 0);
    signal invert_table2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal invert_table2_ce0 : STD_LOGIC;
    signal invert_table2_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal data_7_V_read_1_reg_1806 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal data_6_V_read_1_reg_1811 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_5_V_read_1_reg_1816 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_4_V_read_1_reg_1821 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_3_V_read_1_reg_1826 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_2_V_read_1_reg_1831 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_1_V_read_1_reg_1836 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_0_V_read_1_reg_1841 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_i_i_i_i_fu_362_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_i_i_i_i_reg_1916 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_i_i21_i_i_fu_404_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_i_i21_i_i_reg_1922 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_37_reg_1928 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state8_pp0_stage1_iter2 : BOOLEAN;
    signal ap_block_state11_pp0_stage1_iter3 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal tmp_38_reg_1935 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_reg_1942 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_reg_1949 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_41_reg_1956 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_42_reg_1963 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_43_reg_1970 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_44_reg_1977 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_45_reg_1984 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_46_reg_1991 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_47_reg_1998 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_48_reg_2005 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_49_reg_2012 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_50_reg_2019 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_51_reg_2026 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_52_reg_2033 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_53_reg_2040 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_reg_2047 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_55_reg_2054 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_56_reg_2061 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_2068 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_16_reg_2074 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_10_reg_2080 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_13_reg_2086 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_16_reg_2092 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_19_reg_2098 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_22_reg_2104 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_25_reg_2110 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_28_reg_2116 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_31_reg_2122 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_4_fu_1168_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_4_reg_2148 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_5_fu_1190_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_5_reg_2153 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_6_fu_1212_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_6_reg_2158 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_7_fu_1234_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_7_reg_2163 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_8_fu_1256_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_8_reg_2168 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_9_fu_1278_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_9_reg_2173 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_res_0_V_1_reg_2178 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_0_V_1_reg_2178_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_0_V_1_reg_2178_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_1_V_1_reg_2184 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_1_V_1_reg_2184_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_1_V_1_reg_2184_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_2_V_1_reg_2190 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_2_V_1_reg_2190_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_2_V_1_reg_2190_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_3_V_1_reg_2196 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_3_V_1_reg_2196_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_3_V_1_reg_2196_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_4_V_1_reg_2222 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_4_V_1_reg_2222_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_4_V_1_reg_2222_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_5_V_1_reg_2228 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_5_V_1_reg_2228_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_5_V_1_reg_2228_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_6_V_1_reg_2234 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_6_V_1_reg_2234_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_6_V_1_reg_2234_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_7_V_1_reg_2240 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_7_V_1_reg_2240_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_7_V_1_reg_2240_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_8_V_1_reg_2256 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_8_V_1_reg_2256_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_8_V_1_reg_2256_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_9_V_1_reg_2262 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_9_V_1_reg_2262_pp0_iter2_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_9_V_1_reg_2262_pp0_iter3_reg : STD_LOGIC_VECTOR (16 downto 0);
    signal isneg_1_reg_2268 : STD_LOGIC_VECTOR (0 downto 0);
    signal newsignbit_2_reg_2275 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_reg_2282 : STD_LOGIC_VECTOR (9 downto 0);
    signal inv_exp_sum_V_reg_2293 : STD_LOGIC_VECTOR (17 downto 0);
    signal OP2_V_cast_fu_1567_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal OP2_V_cast_reg_2298 : STD_LOGIC_VECTOR (25 downto 0);
    signal res_0_V_write_assign_reg_2308 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_1_V_write_assign_reg_2313 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_2_V_write_assign_reg_2318 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_3_V_write_assign_reg_2323 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_4_V_write_assign_reg_2328 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_5_V_write_assign_reg_2333 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_6_V_write_assign_reg_2338 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_7_V_write_assign_reg_2343 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_port_reg_data_8_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_data_9_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_296_ap_return : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_296_ap_ce : STD_LOGIC;
    signal grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_312_ap_return : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_312_ap_ce : STD_LOGIC;
    signal exp_res_0_V_fu_86 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_1_V_fu_90 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_2_V_fu_94 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_3_V_fu_98 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_4_V_fu_102 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_5_V_fu_106 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_6_V_fu_110 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_7_V_fu_114 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_8_V_fu_118 : STD_LOGIC_VECTOR (16 downto 0);
    signal exp_res_9_V_fu_122 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_1_15_fu_1068_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal tmp_11_1_fu_1095_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_11_2_fu_1122_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_11_3_fu_1149_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_11_4_fu_1286_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_11_5_fu_1290_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_11_6_fu_1294_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_11_7_fu_1298_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_11_8_fu_1302_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal tmp_11_9_fu_1306_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_6_21_fu_1562_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_i_i_i_i_i_fu_328_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i_i_i_i_i_fu_328_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i_i_i_i_i_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal agg_result_i_i_i_i_i_fu_334_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_i_i_i_i_i_fu_334_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i_i18_i_i_i_fu_342_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i_i18_i_i_i_fu_342_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i_i18_i_i_i_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal agg_result_i_i19_i_i_i_fu_348_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_i_i19_i_i_i_fu_348_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_i_i_i_i_i_fu_334_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_i_i19_i_i_i_fu_348_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i20_i_i_i_fu_356_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_i_i14_i_i_fu_370_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i_i_i14_i_i_fu_370_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i_i_i14_i_i_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal agg_result_i_i_i15_i_i_fu_376_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_i_i_i15_i_i_fu_376_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i_i18_i18_i_i_fu_384_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i_i18_i18_i_i_fu_384_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i_i18_i18_i_i_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal agg_result_i_i19_i19_i_i_fu_390_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_i_i19_i19_i_i_fu_390_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_i_i_i15_i_i_fu_376_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_i_i19_i19_i_i_fu_390_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i20_i20_i_i_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_i_i_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_i13_i_fu_422_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i_i13_i_fu_422_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i_i13_i_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal agg_result_i_i14_i_fu_428_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_i_i14_i_fu_428_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_i_i_i_fu_416_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal agg_result_i_i14_i_fu_428_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_i15_i_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_max_V_fu_442_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_450_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_3_fu_453_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_2_fu_457_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_1_fu_479_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_2_1_fu_482_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_2_fu_504_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_2_2_fu_507_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_3_fu_529_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_2_3_fu_532_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_4_fu_554_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_2_4_fu_557_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_5_fu_579_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_2_5_fu_582_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_6_fu_604_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_2_6_fu_607_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_7_fu_629_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_2_7_fu_632_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_8_fu_654_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_8_fu_654_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_2_8_fu_658_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_9_fu_680_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_9_fu_680_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_2_9_fu_684_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_s_fu_806_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_0_not_fu_820_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_830_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_18_not_fu_844_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_11_fu_854_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_2_not_fu_868_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_12_fu_878_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_3_not_fu_892_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_902_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_4_not_fu_916_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_926_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_5_not_fu_940_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_950_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_6_not_fu_964_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_974_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_7_not_fu_988_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_998_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_8_not_fu_1012_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_1022_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_not_fu_1036_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i_fu_816_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_13_fu_1046_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_8_14_fu_1053_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_fu_1060_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal brmerge_i_i_1_fu_840_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_1_fu_835_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge1_fu_849_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_17_fu_1073_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_9_18_fu_1080_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_1_fu_1087_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal brmerge_i_i_2_fu_864_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_2_fu_859_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge2_fu_873_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_1100_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_12_fu_1107_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_2_fu_1114_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal brmerge_i_i_3_fu_888_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_3_fu_883_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge3_fu_897_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_1127_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_15_fu_1134_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_3_fu_1141_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal brmerge_i_i_4_fu_912_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_4_fu_907_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge4_fu_921_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_1154_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_18_fu_1161_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal brmerge_i_i_5_fu_936_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_5_fu_931_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge5_fu_945_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_1176_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_21_fu_1183_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal brmerge_i_i_6_fu_960_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_6_fu_955_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge6_fu_969_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_1198_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_24_fu_1205_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal brmerge_i_i_7_fu_984_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_7_fu_979_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge7_fu_993_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_1220_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_27_fu_1227_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal brmerge_i_i_8_fu_1008_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_8_fu_1003_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge8_fu_1017_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_1242_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_30_fu_1249_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal brmerge_i_i_9_fu_1032_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_9_fu_1027_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge9_fu_1041_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_fu_1264_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_33_fu_1271_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_i_i_i1_fu_1352_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_i_i_i_19_fu_1356_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_i_i_i1_fu_1352_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_i_i_i_19_fu_1356_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_Val2_24_fu_1360_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_Val2_25_fu_1374_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_25_fu_1374_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_25_fu_1374_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal newsignbit_fu_1380_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isneg_fu_1366_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_61_i_i_i_fu_1388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_not_i_i_i_fu_1406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i_i_i_i_fu_1400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_10_fu_1394_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i_i_fu_1412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_22_mux_i_i_i_fu_1418_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_i_i_i_fu_1426_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_3_fu_1442_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_4_fu_1445_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_7_fu_1448_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal newsignbit_1_fu_1454_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_26_fu_1434_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_27_fu_1462_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_i_i_fu_1470_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_i_i_20_fu_1474_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_Val2_28_fu_1478_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_Val2_29_fu_1492_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_61_i_i_fu_1516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_not_i_i_fu_1530_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i_i2_i_fu_1526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_11_fu_1521_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i1_fu_1535_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_fu_1540_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_36_fu_1547_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_10_fu_1554_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Val2_5_fu_1742_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_1_fu_1749_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_2_fu_1756_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_3_fu_1763_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_4_fu_1770_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_5_fu_1776_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_6_fu_1782_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_7_fu_1788_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_8_fu_1794_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_9_fu_1800_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_fu_1742_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_5_fu_1742_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_5_1_fu_1749_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_5_1_fu_1749_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_5_2_fu_1756_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_5_2_fu_1756_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_5_3_fu_1763_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_5_3_fu_1763_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_5_4_fu_1770_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_5_4_fu_1770_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_5_5_fu_1776_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_5_5_fu_1776_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_5_6_fu_1782_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_5_6_fu_1782_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_5_7_fu_1788_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_5_7_fu_1788_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_5_8_fu_1794_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_5_8_fu_1794_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_5_9_fu_1800_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_5_9_fu_1800_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0_0to3 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0_1to4 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal p_Val2_5_1_fu_1749_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_2_fu_1756_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_3_fu_1763_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_4_fu_1770_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_5_fu_1776_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_6_fu_1782_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_7_fu_1788_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_8_fu_1794_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_9_fu_1800_p00 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_5_fu_1742_p00 : STD_LOGIC_VECTOR (25 downto 0);

    component reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        x_0_V : IN STD_LOGIC_VECTOR (16 downto 0);
        x_1_V : IN STD_LOGIC_VECTOR (16 downto 0);
        x_2_V : IN STD_LOGIC_VECTOR (16 downto 0);
        x_3_V : IN STD_LOGIC_VECTOR (16 downto 0);
        x_4_V : IN STD_LOGIC_VECTOR (16 downto 0);
        x_5_V : IN STD_LOGIC_VECTOR (16 downto 0);
        x_6_V : IN STD_LOGIC_VECTOR (16 downto 0);
        x_7_V : IN STD_LOGIC_VECTOR (16 downto 0);
        x_8_V : IN STD_LOGIC_VECTOR (16 downto 0);
        x_9_V : IN STD_LOGIC_VECTOR (16 downto 0);
        x_V_offset : IN STD_LOGIC_VECTOR (4 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (17 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;


    component myproject_mul_mul_17ns_18s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config9_s_exp_table1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address3 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config9_s_invert_table2 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    exp_table1_U : component softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config9_s_exp_table1
    generic map (
        DataWidth => 17,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_table1_address0,
        ce0 => exp_table1_ce0,
        q0 => exp_table1_q0,
        address1 => exp_table1_address1,
        ce1 => exp_table1_ce1,
        q1 => exp_table1_q1,
        address2 => exp_table1_address2,
        ce2 => exp_table1_ce2,
        q2 => exp_table1_q2,
        address3 => exp_table1_address3,
        ce3 => exp_table1_ce3,
        q3 => exp_table1_q3);

    invert_table2_U : component softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config9_s_invert_table2
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => invert_table2_address0,
        ce0 => invert_table2_ce0,
        q0 => invert_table2_q0);

    grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_296 : component reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        x_0_V => exp_res_0_V_fu_86,
        x_1_V => exp_res_1_V_fu_90,
        x_2_V => exp_res_2_V_fu_94,
        x_3_V => exp_res_3_V_fu_98,
        x_4_V => exp_res_4_V_fu_102,
        x_5_V => exp_res_5_V_fu_106,
        x_6_V => exp_res_6_V_fu_110,
        x_7_V => exp_res_7_V_fu_114,
        x_8_V => exp_res_8_V_fu_118,
        x_9_V => exp_res_9_V_fu_122,
        x_V_offset => ap_const_lv5_0,
        ap_return => grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_296_ap_return,
        ap_ce => grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_296_ap_ce);

    grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_312 : component reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        x_0_V => exp_res_0_V_fu_86,
        x_1_V => exp_res_1_V_fu_90,
        x_2_V => exp_res_2_V_fu_94,
        x_3_V => exp_res_3_V_fu_98,
        x_4_V => exp_res_4_V_fu_102,
        x_5_V => exp_res_5_V_fu_106,
        x_6_V => exp_res_6_V_fu_110,
        x_7_V => exp_res_7_V_fu_114,
        x_8_V => exp_res_8_V_fu_118,
        x_9_V => exp_res_9_V_fu_122,
        x_V_offset => ap_const_lv5_4,
        ap_return => grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_312_ap_return,
        ap_ce => grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_312_ap_ce);

    myproject_mul_mul_17ns_18s_26_1_1_U399 : component myproject_mul_mul_17ns_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 17,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => p_Val2_5_fu_1742_p0,
        din1 => p_Val2_5_fu_1742_p1,
        dout => p_Val2_5_fu_1742_p2);

    myproject_mul_mul_17ns_18s_26_1_1_U400 : component myproject_mul_mul_17ns_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 17,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => p_Val2_5_1_fu_1749_p0,
        din1 => p_Val2_5_1_fu_1749_p1,
        dout => p_Val2_5_1_fu_1749_p2);

    myproject_mul_mul_17ns_18s_26_1_1_U401 : component myproject_mul_mul_17ns_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 17,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => p_Val2_5_2_fu_1756_p0,
        din1 => p_Val2_5_2_fu_1756_p1,
        dout => p_Val2_5_2_fu_1756_p2);

    myproject_mul_mul_17ns_18s_26_1_1_U402 : component myproject_mul_mul_17ns_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 17,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => p_Val2_5_3_fu_1763_p0,
        din1 => p_Val2_5_3_fu_1763_p1,
        dout => p_Val2_5_3_fu_1763_p2);

    myproject_mul_mul_17ns_18s_26_1_1_U403 : component myproject_mul_mul_17ns_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 17,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => p_Val2_5_4_fu_1770_p0,
        din1 => p_Val2_5_4_fu_1770_p1,
        dout => p_Val2_5_4_fu_1770_p2);

    myproject_mul_mul_17ns_18s_26_1_1_U404 : component myproject_mul_mul_17ns_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 17,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => p_Val2_5_5_fu_1776_p0,
        din1 => p_Val2_5_5_fu_1776_p1,
        dout => p_Val2_5_5_fu_1776_p2);

    myproject_mul_mul_17ns_18s_26_1_1_U405 : component myproject_mul_mul_17ns_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 17,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => p_Val2_5_6_fu_1782_p0,
        din1 => p_Val2_5_6_fu_1782_p1,
        dout => p_Val2_5_6_fu_1782_p2);

    myproject_mul_mul_17ns_18s_26_1_1_U406 : component myproject_mul_mul_17ns_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 17,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => p_Val2_5_7_fu_1788_p0,
        din1 => p_Val2_5_7_fu_1788_p1,
        dout => p_Val2_5_7_fu_1788_p2);

    myproject_mul_mul_17ns_18s_26_1_1_U407 : component myproject_mul_mul_17ns_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 17,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => p_Val2_5_8_fu_1794_p0,
        din1 => p_Val2_5_8_fu_1794_p1,
        dout => p_Val2_5_8_fu_1794_p2);

    myproject_mul_mul_17ns_18s_26_1_1_U408 : component myproject_mul_mul_17ns_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 17,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => p_Val2_5_9_fu_1800_p0,
        din1 => p_Val2_5_9_fu_1800_p1,
        dout => p_Val2_5_9_fu_1800_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                elsif (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                OP2_V_cast_reg_2298 <= OP2_V_cast_fu_1567_p1;
                exp_res_4_V_1_reg_2222_pp0_iter2_reg <= exp_res_4_V_1_reg_2222;
                exp_res_4_V_1_reg_2222_pp0_iter3_reg <= exp_res_4_V_1_reg_2222_pp0_iter2_reg;
                exp_res_5_V_1_reg_2228_pp0_iter2_reg <= exp_res_5_V_1_reg_2228;
                exp_res_5_V_1_reg_2228_pp0_iter3_reg <= exp_res_5_V_1_reg_2228_pp0_iter2_reg;
                exp_res_6_V_1_reg_2234_pp0_iter2_reg <= exp_res_6_V_1_reg_2234;
                exp_res_6_V_1_reg_2234_pp0_iter3_reg <= exp_res_6_V_1_reg_2234_pp0_iter2_reg;
                exp_res_7_V_1_reg_2240_pp0_iter2_reg <= exp_res_7_V_1_reg_2240;
                exp_res_7_V_1_reg_2240_pp0_iter3_reg <= exp_res_7_V_1_reg_2240_pp0_iter2_reg;
                isneg_1_reg_2268 <= p_Val2_28_fu_1478_p2(18 downto 18);
                newsignbit_2_reg_2275 <= p_Val2_29_fu_1492_p2(17 downto 17);
                res_0_V_write_assign_reg_2308 <= p_Val2_5_fu_1742_p2(25 downto 10);
                res_1_V_write_assign_reg_2313 <= p_Val2_5_1_fu_1749_p2(25 downto 10);
                res_2_V_write_assign_reg_2318 <= p_Val2_5_2_fu_1756_p2(25 downto 10);
                res_3_V_write_assign_reg_2323 <= p_Val2_5_3_fu_1763_p2(25 downto 10);
                tmp_10_reg_2080 <= p_Val2_2_2_fu_507_p2(15 downto 6);
                tmp_13_reg_2086 <= p_Val2_2_3_fu_532_p2(15 downto 6);
                tmp_16_reg_2092 <= p_Val2_2_4_fu_557_p2(15 downto 6);
                tmp_19_reg_2098 <= p_Val2_2_5_fu_582_p2(15 downto 6);
                tmp_22_reg_2104 <= p_Val2_2_6_fu_607_p2(15 downto 6);
                tmp_25_reg_2110 <= p_Val2_2_7_fu_632_p2(15 downto 6);
                tmp_28_reg_2116 <= p_Val2_2_8_fu_658_p2(15 downto 6);
                tmp_31_reg_2122 <= p_Val2_2_9_fu_684_p2(15 downto 6);
                tmp_34_reg_2282 <= p_Val2_29_fu_1492_p2(17 downto 8);
                tmp_37_reg_1928 <= p_Val2_2_fu_457_p2(16 downto 16);
                tmp_38_reg_1935 <= p_Val2_2_fu_457_p2(15 downto 15);
                tmp_39_reg_1942 <= p_Val2_2_1_fu_482_p2(16 downto 16);
                tmp_40_reg_1949 <= p_Val2_2_1_fu_482_p2(15 downto 15);
                tmp_41_reg_1956 <= p_Val2_2_2_fu_507_p2(16 downto 16);
                tmp_42_reg_1963 <= p_Val2_2_2_fu_507_p2(15 downto 15);
                tmp_43_reg_1970 <= p_Val2_2_3_fu_532_p2(16 downto 16);
                tmp_44_reg_1977 <= p_Val2_2_3_fu_532_p2(15 downto 15);
                tmp_45_reg_1984 <= p_Val2_2_4_fu_557_p2(16 downto 16);
                tmp_46_reg_1991 <= p_Val2_2_4_fu_557_p2(15 downto 15);
                tmp_47_reg_1998 <= p_Val2_2_5_fu_582_p2(16 downto 16);
                tmp_48_reg_2005 <= p_Val2_2_5_fu_582_p2(15 downto 15);
                tmp_49_reg_2012 <= p_Val2_2_6_fu_607_p2(16 downto 16);
                tmp_4_16_reg_2074 <= p_Val2_2_1_fu_482_p2(15 downto 6);
                tmp_50_reg_2019 <= p_Val2_2_6_fu_607_p2(15 downto 15);
                tmp_51_reg_2026 <= p_Val2_2_7_fu_632_p2(16 downto 16);
                tmp_52_reg_2033 <= p_Val2_2_7_fu_632_p2(15 downto 15);
                tmp_53_reg_2040 <= p_Val2_2_8_fu_658_p2(16 downto 16);
                tmp_54_reg_2047 <= p_Val2_2_8_fu_658_p2(15 downto 15);
                tmp_55_reg_2054 <= p_Val2_2_9_fu_684_p2(16 downto 16);
                tmp_56_reg_2061 <= p_Val2_2_9_fu_684_p2(15 downto 15);
                tmp_reg_2068 <= p_Val2_2_fu_457_p2(15 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                agg_result_i_i21_i_i_reg_1922 <= agg_result_i_i21_i_i_fu_404_p3;
                agg_result_i_i_i_i_reg_1916 <= agg_result_i_i_i_i_fu_362_p3;
                data_0_V_read_1_reg_1841 <= data_0_V_read;
                data_1_V_read_1_reg_1836 <= data_1_V_read;
                data_2_V_read_1_reg_1831 <= data_2_V_read;
                data_3_V_read_1_reg_1826 <= data_3_V_read;
                data_4_V_read_1_reg_1821 <= data_4_V_read;
                data_5_V_read_1_reg_1816 <= data_5_V_read;
                data_6_V_read_1_reg_1811 <= data_6_V_read;
                data_7_V_read_1_reg_1806 <= data_7_V_read;
                exp_res_0_V_1_reg_2178_pp0_iter2_reg <= exp_res_0_V_1_reg_2178;
                exp_res_0_V_1_reg_2178_pp0_iter3_reg <= exp_res_0_V_1_reg_2178_pp0_iter2_reg;
                exp_res_1_V_1_reg_2184_pp0_iter2_reg <= exp_res_1_V_1_reg_2184;
                exp_res_1_V_1_reg_2184_pp0_iter3_reg <= exp_res_1_V_1_reg_2184_pp0_iter2_reg;
                exp_res_2_V_1_reg_2190_pp0_iter2_reg <= exp_res_2_V_1_reg_2190;
                exp_res_2_V_1_reg_2190_pp0_iter3_reg <= exp_res_2_V_1_reg_2190_pp0_iter2_reg;
                exp_res_3_V_1_reg_2196_pp0_iter2_reg <= exp_res_3_V_1_reg_2196;
                exp_res_3_V_1_reg_2196_pp0_iter3_reg <= exp_res_3_V_1_reg_2196_pp0_iter2_reg;
                inv_exp_sum_V_reg_2293 <= invert_table2_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_port_reg_data_8_V_read <= data_8_V_read;
                ap_port_reg_data_9_V_read <= data_9_V_read;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                exp_res_0_V_1_reg_2178 <= exp_table1_q0;
                exp_res_1_V_1_reg_2184 <= exp_table1_q1;
                exp_res_2_V_1_reg_2190 <= exp_table1_q2;
                exp_res_3_V_1_reg_2196 <= exp_table1_q3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                exp_res_0_V_fu_86 <= exp_res_0_V_1_reg_2178;
                exp_res_1_V_fu_90 <= exp_res_1_V_1_reg_2184;
                exp_res_2_V_fu_94 <= exp_res_2_V_1_reg_2190;
                exp_res_3_V_fu_98 <= exp_res_3_V_1_reg_2196;
                exp_res_4_V_fu_102 <= exp_res_4_V_1_reg_2222;
                exp_res_5_V_fu_106 <= exp_res_5_V_1_reg_2228;
                exp_res_6_V_fu_110 <= exp_res_6_V_1_reg_2234;
                exp_res_7_V_fu_114 <= exp_res_7_V_1_reg_2240;
                exp_res_8_V_1_reg_2256 <= exp_table1_q0;
                exp_res_8_V_fu_118 <= exp_table1_q0;
                exp_res_9_V_1_reg_2262 <= exp_table1_q1;
                exp_res_9_V_fu_122 <= exp_table1_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                exp_res_4_V_1_reg_2222 <= exp_table1_q0;
                exp_res_5_V_1_reg_2228 <= exp_table1_q1;
                exp_res_6_V_1_reg_2234 <= exp_table1_q2;
                exp_res_7_V_1_reg_2240 <= exp_table1_q3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                exp_res_8_V_1_reg_2256_pp0_iter2_reg <= exp_res_8_V_1_reg_2256;
                exp_res_8_V_1_reg_2256_pp0_iter3_reg <= exp_res_8_V_1_reg_2256_pp0_iter2_reg;
                exp_res_9_V_1_reg_2262_pp0_iter2_reg <= exp_res_9_V_1_reg_2262;
                exp_res_9_V_1_reg_2262_pp0_iter3_reg <= exp_res_9_V_1_reg_2262_pp0_iter2_reg;
                res_4_V_write_assign_reg_2328 <= p_Val2_5_4_fu_1770_p2(25 downto 10);
                res_5_V_write_assign_reg_2333 <= p_Val2_5_5_fu_1776_p2(25 downto 10);
                res_6_V_write_assign_reg_2338 <= p_Val2_5_6_fu_1782_p2(25 downto 10);
                res_7_V_write_assign_reg_2343 <= p_Val2_5_7_fu_1788_p2(25 downto 10);
                y_V_4_reg_2148 <= y_V_4_fu_1168_p3;
                y_V_5_reg_2153 <= y_V_5_fu_1190_p3;
                y_V_6_reg_2158 <= y_V_6_fu_1212_p3;
                y_V_7_reg_2163 <= y_V_7_fu_1234_p3;
                y_V_8_reg_2168 <= y_V_8_fu_1256_p3;
                y_V_9_reg_2173 <= y_V_9_fu_1278_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_block_pp0_stage2_subdone, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0, ap_idle_pp0_1to4, ap_block_pp0_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start = ap_const_logic_0) and (ap_idle_pp0_1to4 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_reset_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_reset_idle_pp0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
        OP2_V_cast_fu_1567_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(inv_exp_sum_V_reg_2293),26));

    agg_result_i_i14_i_fu_428_p1 <= ap_port_reg_data_9_V_read;
    agg_result_i_i14_i_fu_428_p2 <= ap_port_reg_data_8_V_read;
    agg_result_i_i14_i_fu_428_p3 <= 
        agg_result_i_i14_i_fu_428_p1 when (tmp_i_i13_i_fu_422_p2(0) = '1') else 
        agg_result_i_i14_i_fu_428_p2;
    agg_result_i_i19_i19_i_i_fu_390_p1 <= data_7_V_read;
    agg_result_i_i19_i19_i_i_fu_390_p2 <= data_6_V_read;
    agg_result_i_i19_i19_i_i_fu_390_p3 <= 
        agg_result_i_i19_i19_i_i_fu_390_p1 when (tmp_i_i18_i18_i_i_fu_384_p2(0) = '1') else 
        agg_result_i_i19_i19_i_i_fu_390_p2;
    agg_result_i_i19_i_i_i_fu_348_p1 <= data_3_V_read;
    agg_result_i_i19_i_i_i_fu_348_p2 <= data_2_V_read;
    agg_result_i_i19_i_i_i_fu_348_p3 <= 
        agg_result_i_i19_i_i_i_fu_348_p1 when (tmp_i_i18_i_i_i_fu_342_p2(0) = '1') else 
        agg_result_i_i19_i_i_i_fu_348_p2;
    agg_result_i_i21_i_i_fu_404_p3 <= 
        agg_result_i_i19_i19_i_i_fu_390_p3 when (tmp_i20_i20_i_i_fu_398_p2(0) = '1') else 
        agg_result_i_i_i15_i_i_fu_376_p3;
    agg_result_i_i_i15_i_i_fu_376_p1 <= data_5_V_read;
    agg_result_i_i_i15_i_i_fu_376_p2 <= data_4_V_read;
    agg_result_i_i_i15_i_i_fu_376_p3 <= 
        agg_result_i_i_i15_i_i_fu_376_p1 when (tmp_i_i_i14_i_i_fu_370_p2(0) = '1') else 
        agg_result_i_i_i15_i_i_fu_376_p2;
    agg_result_i_i_i_fu_416_p3 <= 
        agg_result_i_i21_i_i_reg_1922 when (tmp_i_i_i_fu_412_p2(0) = '1') else 
        agg_result_i_i_i_i_reg_1916;
    agg_result_i_i_i_i_fu_362_p3 <= 
        agg_result_i_i19_i_i_i_fu_348_p3 when (tmp_i20_i_i_i_fu_356_p2(0) = '1') else 
        agg_result_i_i_i_i_i_fu_334_p3;
    agg_result_i_i_i_i_i_fu_334_p1 <= data_1_V_read;
    agg_result_i_i_i_i_i_fu_334_p2 <= data_0_V_read;
    agg_result_i_i_i_i_i_fu_334_p3 <= 
        agg_result_i_i_i_i_i_fu_334_p1 when (tmp_i_i_i_i_i_fu_328_p2(0) = '1') else 
        agg_result_i_i_i_i_i_fu_334_p2;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_start = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage1_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage2_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage2_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage2_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage1_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage2_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_start = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to3_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to3 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to4_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to4 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to3)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to3 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= res_0_V_write_assign_reg_2308;
    ap_return_1 <= res_1_V_write_assign_reg_2313;
    ap_return_2 <= res_2_V_write_assign_reg_2318;
    ap_return_3 <= res_3_V_write_assign_reg_2323;
    ap_return_4 <= res_4_V_write_assign_reg_2328;
    ap_return_5 <= res_5_V_write_assign_reg_2333;
    ap_return_6 <= res_6_V_write_assign_reg_2338;
    ap_return_7 <= res_7_V_write_assign_reg_2343;
    ap_return_8 <= p_Val2_5_8_fu_1794_p2(25 downto 10);
    ap_return_9 <= p_Val2_5_9_fu_1800_p2(25 downto 10);
    brmerge1_fu_849_p2 <= (tmp_40_reg_1949 or p_Result_18_not_fu_844_p2);
    brmerge2_fu_873_p2 <= (tmp_42_reg_1963 or p_Result_2_not_fu_868_p2);
    brmerge3_fu_897_p2 <= (tmp_44_reg_1977 or p_Result_3_not_fu_892_p2);
    brmerge4_fu_921_p2 <= (tmp_46_reg_1991 or p_Result_4_not_fu_916_p2);
    brmerge5_fu_945_p2 <= (tmp_48_reg_2005 or p_Result_5_not_fu_940_p2);
    brmerge6_fu_969_p2 <= (tmp_50_reg_2019 or p_Result_6_not_fu_964_p2);
    brmerge7_fu_993_p2 <= (tmp_52_reg_2033 or p_Result_7_not_fu_988_p2);
    brmerge8_fu_1017_p2 <= (tmp_54_reg_2047 or p_Result_8_not_fu_1012_p2);
    brmerge9_fu_1041_p2 <= (tmp_56_reg_2061 or p_Result_9_not_fu_1036_p2);
    brmerge_fu_825_p2 <= (tmp_38_reg_1935 or p_Result_0_not_fu_820_p2);
    brmerge_i_i1_fu_1535_p2 <= (p_Result_not_i_i_fu_1530_p2 or newsignbit_2_reg_2275);
    brmerge_i_i_1_fu_840_p2 <= (tmp_40_reg_1949 xor tmp_39_reg_1942);
    brmerge_i_i_2_fu_864_p2 <= (tmp_42_reg_1963 xor tmp_41_reg_1956);
    brmerge_i_i_3_fu_888_p2 <= (tmp_44_reg_1977 xor tmp_43_reg_1970);
    brmerge_i_i_4_fu_912_p2 <= (tmp_46_reg_1991 xor tmp_45_reg_1984);
    brmerge_i_i_5_fu_936_p2 <= (tmp_48_reg_2005 xor tmp_47_reg_1998);
    brmerge_i_i_6_fu_960_p2 <= (tmp_50_reg_2019 xor tmp_49_reg_2012);
    brmerge_i_i_7_fu_984_p2 <= (tmp_52_reg_2033 xor tmp_51_reg_2026);
    brmerge_i_i_8_fu_1008_p2 <= (tmp_54_reg_2047 xor tmp_53_reg_2040);
    brmerge_i_i_9_fu_1032_p2 <= (tmp_56_reg_2061 xor tmp_55_reg_2054);
    brmerge_i_i_fu_816_p2 <= (tmp_38_reg_1935 xor tmp_37_reg_1928);
    brmerge_i_i_i2_i_fu_1526_p2 <= (newsignbit_2_reg_2275 xor isneg_1_reg_2268);
    brmerge_i_i_i_fu_1412_p2 <= (p_Result_not_i_i_i_fu_1406_p2 or newsignbit_fu_1380_p3);
    brmerge_i_i_i_i_i_fu_1400_p2 <= (newsignbit_fu_1380_p3 xor isneg_fu_1366_p3);

    exp_table1_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, tmp_1_15_fu_1068_p1, ap_block_pp0_stage2, tmp_11_4_fu_1286_p1, tmp_11_8_fu_1302_p1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            exp_table1_address0 <= tmp_11_8_fu_1302_p1(10 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_address0 <= tmp_11_4_fu_1286_p1(10 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            exp_table1_address0 <= tmp_1_15_fu_1068_p1(10 - 1 downto 0);
        else 
            exp_table1_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    exp_table1_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage2, tmp_11_1_fu_1095_p1, tmp_11_5_fu_1290_p1, ap_block_pp0_stage1, tmp_11_9_fu_1306_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            exp_table1_address1 <= tmp_11_9_fu_1306_p1(10 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_address1 <= tmp_11_5_fu_1290_p1(10 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            exp_table1_address1 <= tmp_11_1_fu_1095_p1(10 - 1 downto 0);
        else 
            exp_table1_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    exp_table1_address2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, tmp_11_2_fu_1122_p1, tmp_11_6_fu_1294_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_address2 <= tmp_11_6_fu_1294_p1(10 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            exp_table1_address2 <= tmp_11_2_fu_1122_p1(10 - 1 downto 0);
        else 
            exp_table1_address2 <= "XXXXXXXXXX";
        end if; 
    end process;


    exp_table1_address3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, tmp_11_3_fu_1149_p1, tmp_11_7_fu_1298_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_address3 <= tmp_11_7_fu_1298_p1(10 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            exp_table1_address3 <= tmp_11_3_fu_1149_p1(10 - 1 downto 0);
        else 
            exp_table1_address3 <= "XXXXXXXXXX";
        end if; 
    end process;


    exp_table1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)))) then 
            exp_table1_ce0 <= ap_const_logic_1;
        else 
            exp_table1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)))) then 
            exp_table1_ce1 <= ap_const_logic_1;
        else 
            exp_table1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            exp_table1_ce2 <= ap_const_logic_1;
        else 
            exp_table1_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            exp_table1_ce3 <= ap_const_logic_1;
        else 
            exp_table1_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_296_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)))) then 
            grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_296_ap_ce <= ap_const_logic_1;
        else 
            grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_296_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_312_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)))) then 
            grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_312_ap_ce <= ap_const_logic_1;
        else 
            grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_312_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    invert_table2_address0 <= tmp_6_21_fu_1562_p1(10 - 1 downto 0);

    invert_table2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            invert_table2_ce0 <= ap_const_logic_1;
        else 
            invert_table2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    isneg_fu_1366_p3 <= p_Val2_24_fu_1360_p2(18 downto 18);
    newsignbit_1_fu_1454_p3 <= p_Val2_7_fu_1448_p2(17 downto 17);
    newsignbit_fu_1380_p3 <= p_Val2_25_fu_1374_p2(17 downto 17);
    p_Result_0_not_fu_820_p2 <= (tmp_37_reg_1928 xor ap_const_lv1_1);
    p_Result_18_not_fu_844_p2 <= (tmp_39_reg_1942 xor ap_const_lv1_1);
    p_Result_2_not_fu_868_p2 <= (tmp_41_reg_1956 xor ap_const_lv1_1);
    p_Result_3_not_fu_892_p2 <= (tmp_43_reg_1970 xor ap_const_lv1_1);
    p_Result_4_not_fu_916_p2 <= (tmp_45_reg_1984 xor ap_const_lv1_1);
    p_Result_5_not_fu_940_p2 <= (tmp_47_reg_1998 xor ap_const_lv1_1);
    p_Result_6_not_fu_964_p2 <= (tmp_49_reg_2012 xor ap_const_lv1_1);
    p_Result_7_not_fu_988_p2 <= (tmp_51_reg_2026 xor ap_const_lv1_1);
    p_Result_8_not_fu_1012_p2 <= (tmp_53_reg_2040 xor ap_const_lv1_1);
    p_Result_9_not_fu_1036_p2 <= (tmp_55_reg_2054 xor ap_const_lv1_1);
    p_Result_not_i_i_fu_1530_p2 <= (isneg_1_reg_2268 xor ap_const_lv1_1);
    p_Result_not_i_i_i_fu_1406_p2 <= (isneg_fu_1366_p3 xor ap_const_lv1_1);
    p_Val2_22_mux_i_i_i_fu_1418_p3 <= 
        ap_const_lv18_1FFFF when (brmerge_i_i_i_i_i_fu_1400_p2(0) = '1') else 
        p_Val2_25_fu_1374_p2;
    p_Val2_24_fu_1360_p2 <= std_logic_vector(signed(tmp_i_i_i1_fu_1352_p1) + signed(tmp_i_i_i_19_fu_1356_p1));
    p_Val2_25_fu_1374_p0 <= grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_312_ap_return;
    p_Val2_25_fu_1374_p1 <= grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_296_ap_return;
    p_Val2_25_fu_1374_p2 <= std_logic_vector(signed(p_Val2_25_fu_1374_p0) + signed(p_Val2_25_fu_1374_p1));
    p_Val2_26_fu_1434_p3 <= 
        p_Val2_22_mux_i_i_i_fu_1418_p3 when (brmerge_i_i_i_fu_1412_p2(0) = '1') else 
        p_Val2_i_i_i_fu_1426_p3;
    p_Val2_27_fu_1462_p3 <= 
        ap_const_lv18_1FFFF when (newsignbit_1_fu_1454_p3(0) = '1') else 
        p_Val2_7_fu_1448_p2;
    p_Val2_28_fu_1478_p2 <= std_logic_vector(signed(tmp_i_i_fu_1470_p1) + signed(tmp_i_i_20_fu_1474_p1));
    p_Val2_29_fu_1492_p2 <= std_logic_vector(signed(p_Val2_27_fu_1462_p3) + signed(p_Val2_26_fu_1434_p3));
    p_Val2_2_1_fu_482_p2 <= std_logic_vector(signed(tmp_2_1_fu_479_p1) - signed(tmp_3_fu_453_p1));
    p_Val2_2_2_fu_507_p2 <= std_logic_vector(signed(tmp_2_2_fu_504_p1) - signed(tmp_3_fu_453_p1));
    p_Val2_2_3_fu_532_p2 <= std_logic_vector(signed(tmp_2_3_fu_529_p1) - signed(tmp_3_fu_453_p1));
    p_Val2_2_4_fu_557_p2 <= std_logic_vector(signed(tmp_2_4_fu_554_p1) - signed(tmp_3_fu_453_p1));
    p_Val2_2_5_fu_582_p2 <= std_logic_vector(signed(tmp_2_5_fu_579_p1) - signed(tmp_3_fu_453_p1));
    p_Val2_2_6_fu_607_p2 <= std_logic_vector(signed(tmp_2_6_fu_604_p1) - signed(tmp_3_fu_453_p1));
    p_Val2_2_7_fu_632_p2 <= std_logic_vector(signed(tmp_2_7_fu_629_p1) - signed(tmp_3_fu_453_p1));
    p_Val2_2_8_fu_658_p2 <= std_logic_vector(signed(tmp_2_8_fu_654_p1) - signed(tmp_3_fu_453_p1));
    p_Val2_2_9_fu_684_p2 <= std_logic_vector(signed(tmp_2_9_fu_680_p1) - signed(tmp_3_fu_453_p1));
    p_Val2_2_fu_457_p2 <= std_logic_vector(signed(tmp_2_fu_450_p1) - signed(tmp_3_fu_453_p1));
    p_Val2_3_fu_1442_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_8_V_1_reg_2256),18));
    p_Val2_4_fu_1445_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_9_V_1_reg_2262),18));
    p_Val2_5_1_fu_1749_p0 <= p_Val2_5_1_fu_1749_p00(17 - 1 downto 0);
    p_Val2_5_1_fu_1749_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_1_V_1_reg_2184_pp0_iter3_reg),26));
    p_Val2_5_1_fu_1749_p1 <= OP2_V_cast_fu_1567_p1(18 - 1 downto 0);
    p_Val2_5_2_fu_1756_p0 <= p_Val2_5_2_fu_1756_p00(17 - 1 downto 0);
    p_Val2_5_2_fu_1756_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_2_V_1_reg_2190_pp0_iter3_reg),26));
    p_Val2_5_2_fu_1756_p1 <= OP2_V_cast_fu_1567_p1(18 - 1 downto 0);
    p_Val2_5_3_fu_1763_p0 <= p_Val2_5_3_fu_1763_p00(17 - 1 downto 0);
    p_Val2_5_3_fu_1763_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_3_V_1_reg_2196_pp0_iter3_reg),26));
    p_Val2_5_3_fu_1763_p1 <= OP2_V_cast_fu_1567_p1(18 - 1 downto 0);
    p_Val2_5_4_fu_1770_p0 <= p_Val2_5_4_fu_1770_p00(17 - 1 downto 0);
    p_Val2_5_4_fu_1770_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_4_V_1_reg_2222_pp0_iter3_reg),26));
    p_Val2_5_4_fu_1770_p1 <= OP2_V_cast_reg_2298(18 - 1 downto 0);
    p_Val2_5_5_fu_1776_p0 <= p_Val2_5_5_fu_1776_p00(17 - 1 downto 0);
    p_Val2_5_5_fu_1776_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_5_V_1_reg_2228_pp0_iter3_reg),26));
    p_Val2_5_5_fu_1776_p1 <= OP2_V_cast_reg_2298(18 - 1 downto 0);
    p_Val2_5_6_fu_1782_p0 <= p_Val2_5_6_fu_1782_p00(17 - 1 downto 0);
    p_Val2_5_6_fu_1782_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_6_V_1_reg_2234_pp0_iter3_reg),26));
    p_Val2_5_6_fu_1782_p1 <= OP2_V_cast_reg_2298(18 - 1 downto 0);
    p_Val2_5_7_fu_1788_p0 <= p_Val2_5_7_fu_1788_p00(17 - 1 downto 0);
    p_Val2_5_7_fu_1788_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_7_V_1_reg_2240_pp0_iter3_reg),26));
    p_Val2_5_7_fu_1788_p1 <= OP2_V_cast_reg_2298(18 - 1 downto 0);
    p_Val2_5_8_fu_1794_p0 <= p_Val2_5_8_fu_1794_p00(17 - 1 downto 0);
    p_Val2_5_8_fu_1794_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_8_V_1_reg_2256_pp0_iter3_reg),26));
    p_Val2_5_8_fu_1794_p1 <= OP2_V_cast_reg_2298(18 - 1 downto 0);
    p_Val2_5_9_fu_1800_p0 <= p_Val2_5_9_fu_1800_p00(17 - 1 downto 0);
    p_Val2_5_9_fu_1800_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_9_V_1_reg_2262_pp0_iter3_reg),26));
    p_Val2_5_9_fu_1800_p1 <= OP2_V_cast_reg_2298(18 - 1 downto 0);
    p_Val2_5_fu_1742_p0 <= p_Val2_5_fu_1742_p00(17 - 1 downto 0);
    p_Val2_5_fu_1742_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(exp_res_0_V_1_reg_2178_pp0_iter3_reg),26));
    p_Val2_5_fu_1742_p1 <= OP2_V_cast_fu_1567_p1(18 - 1 downto 0);
    p_Val2_7_fu_1448_p2 <= std_logic_vector(unsigned(p_Val2_3_fu_1442_p1) + unsigned(p_Val2_4_fu_1445_p1));
    p_Val2_i_i_i_fu_1426_p3 <= 
        ap_const_lv18_20000 when (underflow_10_fu_1394_p2(0) = '1') else 
        p_Val2_25_fu_1374_p2;
    tmp_11_1_fu_1095_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_1_fu_1087_p3),64));
    tmp_11_2_fu_1122_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_2_fu_1114_p3),64));
    tmp_11_3_fu_1149_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_3_fu_1141_p3),64));
    tmp_11_4_fu_1286_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_4_reg_2148),64));
    tmp_11_5_fu_1290_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_5_reg_2153),64));
    tmp_11_6_fu_1294_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_6_reg_2158),64));
    tmp_11_7_fu_1298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_7_reg_2163),64));
    tmp_11_8_fu_1302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_8_reg_2168),64));
    tmp_11_9_fu_1306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_9_reg_2173),64));
    tmp_11_fu_1100_p3 <= 
        ap_const_lv10_1FF when (brmerge_i_i_2_fu_864_p2(0) = '1') else 
        tmp_10_reg_2080;
    tmp_12_fu_1107_p3 <= 
        ap_const_lv10_200 when (underflow_2_fu_859_p2(0) = '1') else 
        tmp_10_reg_2080;
    tmp_14_fu_1127_p3 <= 
        ap_const_lv10_1FF when (brmerge_i_i_3_fu_888_p2(0) = '1') else 
        tmp_13_reg_2086;
    tmp_15_fu_1134_p3 <= 
        ap_const_lv10_200 when (underflow_3_fu_883_p2(0) = '1') else 
        tmp_13_reg_2086;
    tmp_17_fu_1154_p3 <= 
        ap_const_lv10_1FF when (brmerge_i_i_4_fu_912_p2(0) = '1') else 
        tmp_16_reg_2092;
    tmp_18_fu_1161_p3 <= 
        ap_const_lv10_200 when (underflow_4_fu_907_p2(0) = '1') else 
        tmp_16_reg_2092;
    tmp_1_15_fu_1068_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_fu_1060_p3),64));
    tmp_1_fu_830_p2 <= (tmp_40_reg_1949 xor ap_const_lv1_1);
    tmp_20_fu_1176_p3 <= 
        ap_const_lv10_1FF when (brmerge_i_i_5_fu_936_p2(0) = '1') else 
        tmp_19_reg_2098;
    tmp_21_fu_1183_p3 <= 
        ap_const_lv10_200 when (underflow_5_fu_931_p2(0) = '1') else 
        tmp_19_reg_2098;
    tmp_23_fu_1198_p3 <= 
        ap_const_lv10_1FF when (brmerge_i_i_6_fu_960_p2(0) = '1') else 
        tmp_22_reg_2104;
    tmp_24_fu_1205_p3 <= 
        ap_const_lv10_200 when (underflow_6_fu_955_p2(0) = '1') else 
        tmp_22_reg_2104;
    tmp_26_fu_1220_p3 <= 
        ap_const_lv10_1FF when (brmerge_i_i_7_fu_984_p2(0) = '1') else 
        tmp_25_reg_2110;
    tmp_27_fu_1227_p3 <= 
        ap_const_lv10_200 when (underflow_7_fu_979_p2(0) = '1') else 
        tmp_25_reg_2110;
    tmp_29_fu_1242_p3 <= 
        ap_const_lv10_1FF when (brmerge_i_i_8_fu_1008_p2(0) = '1') else 
        tmp_28_reg_2116;
    tmp_2_11_fu_854_p2 <= (tmp_42_reg_1963 xor ap_const_lv1_1);
        tmp_2_1_fu_479_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_1_V_read_1_reg_1836),17));

        tmp_2_2_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_2_V_read_1_reg_1831),17));

        tmp_2_3_fu_529_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_3_V_read_1_reg_1826),17));

        tmp_2_4_fu_554_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_4_V_read_1_reg_1821),17));

        tmp_2_5_fu_579_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_5_V_read_1_reg_1816),17));

        tmp_2_6_fu_604_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_6_V_read_1_reg_1811),17));

        tmp_2_7_fu_629_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_7_V_read_1_reg_1806),17));

    tmp_2_8_fu_654_p0 <= ap_port_reg_data_8_V_read;
        tmp_2_8_fu_654_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_8_fu_654_p0),17));

    tmp_2_9_fu_680_p0 <= ap_port_reg_data_9_V_read;
        tmp_2_9_fu_680_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_9_fu_680_p0),17));

        tmp_2_fu_450_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_0_V_read_1_reg_1841),17));

    tmp_30_fu_1249_p3 <= 
        ap_const_lv10_200 when (underflow_8_fu_1003_p2(0) = '1') else 
        tmp_28_reg_2116;
    tmp_32_fu_1264_p3 <= 
        ap_const_lv10_1FF when (brmerge_i_i_9_fu_1032_p2(0) = '1') else 
        tmp_31_reg_2122;
    tmp_33_fu_1271_p3 <= 
        ap_const_lv10_200 when (underflow_9_fu_1027_p2(0) = '1') else 
        tmp_31_reg_2122;
    tmp_35_fu_1540_p3 <= 
        ap_const_lv10_1FF when (brmerge_i_i_i2_i_fu_1526_p2(0) = '1') else 
        tmp_34_reg_2282;
    tmp_36_fu_1547_p3 <= 
        ap_const_lv10_200 when (underflow_11_fu_1521_p2(0) = '1') else 
        tmp_34_reg_2282;
    tmp_3_12_fu_878_p2 <= (tmp_44_reg_1977 xor ap_const_lv1_1);
        tmp_3_fu_453_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_max_V_fu_442_p3),17));

    tmp_4_fu_902_p2 <= (tmp_46_reg_1991 xor ap_const_lv1_1);
    tmp_5_13_fu_1046_p3 <= 
        ap_const_lv10_1FF when (brmerge_i_i_fu_816_p2(0) = '1') else 
        tmp_reg_2068;
    tmp_5_fu_926_p2 <= (tmp_48_reg_2005 xor ap_const_lv1_1);
    tmp_61_i_i_fu_1516_p2 <= (newsignbit_2_reg_2275 xor ap_const_lv1_1);
    tmp_61_i_i_i_fu_1388_p2 <= (newsignbit_fu_1380_p3 xor ap_const_lv1_1);
    tmp_6_21_fu_1562_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_10_fu_1554_p3),64));
    tmp_6_fu_950_p2 <= (tmp_50_reg_2019 xor ap_const_lv1_1);
    tmp_7_17_fu_1073_p3 <= 
        ap_const_lv10_1FF when (brmerge_i_i_1_fu_840_p2(0) = '1') else 
        tmp_4_16_reg_2074;
    tmp_7_fu_974_p2 <= (tmp_52_reg_2033 xor ap_const_lv1_1);
    tmp_8_14_fu_1053_p3 <= 
        ap_const_lv10_200 when (underflow_fu_811_p2(0) = '1') else 
        tmp_reg_2068;
    tmp_8_fu_998_p2 <= (tmp_54_reg_2047 xor ap_const_lv1_1);
    tmp_9_18_fu_1080_p3 <= 
        ap_const_lv10_200 when (underflow_1_fu_835_p2(0) = '1') else 
        tmp_4_16_reg_2074;
    tmp_9_fu_1022_p2 <= (tmp_56_reg_2061 xor ap_const_lv1_1);
    tmp_i15_i_fu_436_p2 <= "1" when (signed(agg_result_i_i_i_fu_416_p3) < signed(agg_result_i_i14_i_fu_428_p3)) else "0";
    tmp_i20_i20_i_i_fu_398_p2 <= "1" when (signed(agg_result_i_i_i15_i_i_fu_376_p3) < signed(agg_result_i_i19_i19_i_i_fu_390_p3)) else "0";
    tmp_i20_i_i_i_fu_356_p2 <= "1" when (signed(agg_result_i_i_i_i_i_fu_334_p3) < signed(agg_result_i_i19_i_i_i_fu_348_p3)) else "0";
    tmp_i_i13_i_fu_422_p0 <= ap_port_reg_data_8_V_read;
    tmp_i_i13_i_fu_422_p1 <= ap_port_reg_data_9_V_read;
    tmp_i_i13_i_fu_422_p2 <= "1" when (signed(tmp_i_i13_i_fu_422_p0) < signed(tmp_i_i13_i_fu_422_p1)) else "0";
    tmp_i_i18_i18_i_i_fu_384_p0 <= data_6_V_read;
    tmp_i_i18_i18_i_i_fu_384_p1 <= data_7_V_read;
    tmp_i_i18_i18_i_i_fu_384_p2 <= "1" when (signed(tmp_i_i18_i18_i_i_fu_384_p0) < signed(tmp_i_i18_i18_i_i_fu_384_p1)) else "0";
    tmp_i_i18_i_i_i_fu_342_p0 <= data_2_V_read;
    tmp_i_i18_i_i_i_fu_342_p1 <= data_3_V_read;
    tmp_i_i18_i_i_i_fu_342_p2 <= "1" when (signed(tmp_i_i18_i_i_i_fu_342_p0) < signed(tmp_i_i18_i_i_i_fu_342_p1)) else "0";
        tmp_i_i_20_fu_1474_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_27_fu_1462_p3),19));

        tmp_i_i_fu_1470_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_26_fu_1434_p3),19));

    tmp_i_i_i14_i_i_fu_370_p0 <= data_4_V_read;
    tmp_i_i_i14_i_i_fu_370_p1 <= data_5_V_read;
    tmp_i_i_i14_i_i_fu_370_p2 <= "1" when (signed(tmp_i_i_i14_i_i_fu_370_p0) < signed(tmp_i_i_i14_i_i_fu_370_p1)) else "0";
    tmp_i_i_i1_fu_1352_p0 <= grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_296_ap_return;
        tmp_i_i_i1_fu_1352_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_i_i_i1_fu_1352_p0),19));

    tmp_i_i_i_19_fu_1356_p0 <= grp_reduce_ap_fixed_18_8_0_0_0_4_Op_add_ap_fixed_18_8_0_0_0_s_fu_312_ap_return;
        tmp_i_i_i_19_fu_1356_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_i_i_i_19_fu_1356_p0),19));

    tmp_i_i_i_fu_412_p2 <= "1" when (signed(agg_result_i_i_i_i_reg_1916) < signed(agg_result_i_i21_i_i_reg_1922)) else "0";
    tmp_i_i_i_i_i_fu_328_p0 <= data_0_V_read;
    tmp_i_i_i_i_i_fu_328_p1 <= data_1_V_read;
    tmp_i_i_i_i_i_fu_328_p2 <= "1" when (signed(tmp_i_i_i_i_i_fu_328_p0) < signed(tmp_i_i_i_i_i_fu_328_p1)) else "0";
    tmp_s_fu_806_p2 <= (tmp_38_reg_1935 xor ap_const_lv1_1);
    underflow_10_fu_1394_p2 <= (tmp_61_i_i_i_fu_1388_p2 and isneg_fu_1366_p3);
    underflow_11_fu_1521_p2 <= (tmp_61_i_i_fu_1516_p2 and isneg_1_reg_2268);
    underflow_1_fu_835_p2 <= (tmp_39_reg_1942 and tmp_1_fu_830_p2);
    underflow_2_fu_859_p2 <= (tmp_41_reg_1956 and tmp_2_11_fu_854_p2);
    underflow_3_fu_883_p2 <= (tmp_43_reg_1970 and tmp_3_12_fu_878_p2);
    underflow_4_fu_907_p2 <= (tmp_4_fu_902_p2 and tmp_45_reg_1984);
    underflow_5_fu_931_p2 <= (tmp_5_fu_926_p2 and tmp_47_reg_1998);
    underflow_6_fu_955_p2 <= (tmp_6_fu_950_p2 and tmp_49_reg_2012);
    underflow_7_fu_979_p2 <= (tmp_7_fu_974_p2 and tmp_51_reg_2026);
    underflow_8_fu_1003_p2 <= (tmp_8_fu_998_p2 and tmp_53_reg_2040);
    underflow_9_fu_1027_p2 <= (tmp_9_fu_1022_p2 and tmp_55_reg_2054);
    underflow_fu_811_p2 <= (tmp_s_fu_806_p2 and tmp_37_reg_1928);
    x_max_V_fu_442_p3 <= 
        agg_result_i_i14_i_fu_428_p3 when (tmp_i15_i_fu_436_p2(0) = '1') else 
        agg_result_i_i_i_fu_416_p3;
    y_V_10_fu_1554_p3 <= 
        tmp_35_fu_1540_p3 when (brmerge_i_i1_fu_1535_p2(0) = '1') else 
        tmp_36_fu_1547_p3;
    y_V_1_fu_1087_p3 <= 
        tmp_7_17_fu_1073_p3 when (brmerge1_fu_849_p2(0) = '1') else 
        tmp_9_18_fu_1080_p3;
    y_V_2_fu_1114_p3 <= 
        tmp_11_fu_1100_p3 when (brmerge2_fu_873_p2(0) = '1') else 
        tmp_12_fu_1107_p3;
    y_V_3_fu_1141_p3 <= 
        tmp_14_fu_1127_p3 when (brmerge3_fu_897_p2(0) = '1') else 
        tmp_15_fu_1134_p3;
    y_V_4_fu_1168_p3 <= 
        tmp_17_fu_1154_p3 when (brmerge4_fu_921_p2(0) = '1') else 
        tmp_18_fu_1161_p3;
    y_V_5_fu_1190_p3 <= 
        tmp_20_fu_1176_p3 when (brmerge5_fu_945_p2(0) = '1') else 
        tmp_21_fu_1183_p3;
    y_V_6_fu_1212_p3 <= 
        tmp_23_fu_1198_p3 when (brmerge6_fu_969_p2(0) = '1') else 
        tmp_24_fu_1205_p3;
    y_V_7_fu_1234_p3 <= 
        tmp_26_fu_1220_p3 when (brmerge7_fu_993_p2(0) = '1') else 
        tmp_27_fu_1227_p3;
    y_V_8_fu_1256_p3 <= 
        tmp_29_fu_1242_p3 when (brmerge8_fu_1017_p2(0) = '1') else 
        tmp_30_fu_1249_p3;
    y_V_9_fu_1278_p3 <= 
        tmp_32_fu_1264_p3 when (brmerge9_fu_1041_p2(0) = '1') else 
        tmp_33_fu_1271_p3;
    y_V_fu_1060_p3 <= 
        tmp_5_13_fu_1046_p3 when (brmerge_fu_825_p2(0) = '1') else 
        tmp_8_14_fu_1053_p3;
end behav;
