// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->
    typedef struct {
        float array[784];
        long long unsigned int ndim;
        long long unsigned int numel;
        long long unsigned int shape[5];
       } k2c_tensor2;

          typedef struct {
              long long unsigned int ndim;
              long long unsigned int numel;
              long long unsigned int shape[5];
             } k2c_tensor;

extern float dense_output_array[100];

extern float dense_input_input_array[784];

extern k2c_tensor dense_input_input;

extern float dense_fwork[79184];

extern float dense_3_output_array[10];

extern k2c_tensor dense_3_output;

extern float dense_3_fwork[275];

extern float dense_2_output_array[25];

extern float dense_2_fwork[1300];

extern float dense_1_output_array[50];

extern float dense_1_fwork[5100];



// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "dense_input_input_array"
#define AUTOTB_TVIN_dense_input_input_array  "../tv/cdatafile/c.vlsiModel.autotvin_dense_input_input_array.dat"
// wrapc file define: "dense_input_input_ndim"
#define AUTOTB_TVIN_dense_input_input_ndim  "../tv/cdatafile/c.vlsiModel.autotvin_dense_input_input_ndim.dat"
// wrapc file define: "dense_input_input_numel"
#define AUTOTB_TVIN_dense_input_input_numel  "../tv/cdatafile/c.vlsiModel.autotvin_dense_input_input_numel.dat"
// wrapc file define: "dense_input_input_shape"
#define AUTOTB_TVIN_dense_input_input_shape  "../tv/cdatafile/c.vlsiModel.autotvin_dense_input_input_shape.dat"
// wrapc file define: "dense_3_output_array"
#define AUTOTB_TVOUT_dense_3_output_array  "../tv/cdatafile/c.vlsiModel.autotvout_dense_3_output_array.dat"
#define AUTOTB_TVIN_dense_3_output_array  "../tv/cdatafile/c.vlsiModel.autotvin_dense_3_output_array.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "dense_3_output_array"
#define AUTOTB_TVOUT_PC_dense_3_output_array  "../tv/rtldatafile/rtl.vlsiModel.autotvout_dense_3_output_array.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			dense_input_input_array_depth = 0;
			dense_input_input_ndim_depth = 0;
			dense_input_input_numel_depth = 0;
			dense_input_input_shape_depth = 0;
			dense_3_output_array_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{dense_input_input_array " << dense_input_input_array_depth << "}\n";
			total_list << "{dense_input_input_ndim " << dense_input_input_ndim_depth << "}\n";
			total_list << "{dense_input_input_numel " << dense_input_input_numel_depth << "}\n";
			total_list << "{dense_input_input_shape " << dense_input_input_shape_depth << "}\n";
			total_list << "{dense_3_output_array " << dense_3_output_array_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int dense_input_input_array_depth;
		int dense_input_input_ndim_depth;
		int dense_input_input_numel_depth;
		int dense_input_input_shape_depth;
		int dense_3_output_array_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};

extern "C" void vlsiModel (
k2c_tensor2* dense_input_input_,
k2c_tensor2* dense_3_output_);

extern "C" void AESL_WRAP_vlsiModel (
k2c_tensor2* dense_input_input_,
k2c_tensor2* dense_3_output_)
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;


		// output port post check: "dense_3_output_array"
		aesl_fh.read(AUTOTB_TVOUT_PC_dense_3_output_array, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_dense_3_output_array, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_dense_3_output_array, AESL_token); // data

			sc_bv<32> *dense_3_output_array_pc_buffer = new sc_bv<32>[784];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'dense_3_output_array', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'dense_3_output_array', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					dense_3_output_array_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_dense_3_output_array, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_dense_3_output_array))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: dense_3_output_array
				{
					// bitslice(31, 0)
					// {
						// celement: dense_3_output_.array(31, 0)
						// {
							sc_lv<32>* dense_3_output__array_lv0_0_783_1 = new sc_lv<32>[784];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: dense_3_output_.array(31, 0)
						{
							// carray: (0) => (783) @ (1)
							for (int i_0 = 0; i_0 <= 783; i_0 += 1)
							{
								if (&(dense_3_output_->array[0]) != NULL) // check the null address if the c port is array or others
								{
									dense_3_output__array_lv0_0_783_1[hls_map_index].range(31, 0) = sc_bv<32>(dense_3_output_array_pc_buffer[hls_map_index].range(31, 0));
									hls_map_index++;
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: dense_3_output_.array(31, 0)
						{
							// carray: (0) => (783) @ (1)
							for (int i_0 = 0; i_0 <= 783; i_0 += 1)
							{
								// sub                    : i_0
								// ori_name               : dense_3_output_->array[i_0]
								// sub_1st_elem           : 0
								// ori_name_1st_elem      : dense_3_output_->array[0]
								// output_left_conversion : *(int*)&dense_3_output_->array[i_0]
								// output_type_conversion : (dense_3_output__array_lv0_0_783_1[hls_map_index]).to_uint64()
								if (&(dense_3_output_->array[0]) != NULL) // check the null address if the c port is array or others
								{
									*(int*)&dense_3_output_->array[i_0] = (dense_3_output__array_lv0_0_783_1[hls_map_index]).to_uint64();
									hls_map_index++;
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] dense_3_output_array_pc_buffer;
		}

		AESL_transaction_pc++;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "dense_input_input_array"
		char* tvin_dense_input_input_array = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_dense_input_input_array);

		// "dense_input_input_ndim"
		char* tvin_dense_input_input_ndim = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_dense_input_input_ndim);

		// "dense_input_input_numel"
		char* tvin_dense_input_input_numel = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_dense_input_input_numel);

		// "dense_input_input_shape"
		char* tvin_dense_input_input_shape = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_dense_input_input_shape);

		// "dense_3_output_array"
		char* tvin_dense_3_output_array = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_dense_3_output_array);
		char* tvout_dense_3_output_array = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_dense_3_output_array);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_dense_input_input_array, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_dense_input_input_array, tvin_dense_input_input_array);

		sc_bv<32>* dense_input_input_array_tvin_wrapc_buffer = new sc_bv<32>[784];

		// RTL Name: dense_input_input_array
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: dense_input_input_.array(31, 0)
				{
					// carray: (0) => (783) @ (1)
					for (int i_0 = 0; i_0 <= 783; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : dense_input_input_->array[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : dense_input_input_->array[0]
						// regulate_c_name       : dense_input_input__array
						// input_type_conversion : *(int*)&dense_input_input_->array[i_0]
						if (&(dense_input_input_->array[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> dense_input_input__array_tmp_mem;
							dense_input_input__array_tmp_mem = *(int*)&dense_input_input_->array[i_0];
							dense_input_input_array_tvin_wrapc_buffer[hls_map_index].range(31, 0) = dense_input_input__array_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 784; i++)
		{
			sprintf(tvin_dense_input_input_array, "%s\n", (dense_input_input_array_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_dense_input_input_array, tvin_dense_input_input_array);
		}

		tcl_file.set_num(784, &tcl_file.dense_input_input_array_depth);
		sprintf(tvin_dense_input_input_array, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_dense_input_input_array, tvin_dense_input_input_array);

		// release memory allocation
		delete [] dense_input_input_array_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_dense_input_input_ndim, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_dense_input_input_ndim, tvin_dense_input_input_ndim);

		sc_bv<64>* dense_input_input_ndim_tvin_wrapc_buffer = new sc_bv<64>[1];

		// RTL Name: dense_input_input_ndim
		{
			// bitslice(63, 0)
			{
				int hls_map_index = 0;
				// celement: dense_input_input_.ndim(63, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : dense_input_input_->ndim
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : dense_input_input_->ndim
						// regulate_c_name       : dense_input_input__ndim
						// input_type_conversion : dense_input_input_->ndim
						if (&(dense_input_input_->ndim) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<64> dense_input_input__ndim_tmp_mem;
							dense_input_input__ndim_tmp_mem = dense_input_input_->ndim;
							dense_input_input_ndim_tvin_wrapc_buffer[hls_map_index].range(63, 0) = dense_input_input__ndim_tmp_mem.range(63, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_dense_input_input_ndim, "%s\n", (dense_input_input_ndim_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_dense_input_input_ndim, tvin_dense_input_input_ndim);
		}

		tcl_file.set_num(1, &tcl_file.dense_input_input_ndim_depth);
		sprintf(tvin_dense_input_input_ndim, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_dense_input_input_ndim, tvin_dense_input_input_ndim);

		// release memory allocation
		delete [] dense_input_input_ndim_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_dense_input_input_numel, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_dense_input_input_numel, tvin_dense_input_input_numel);

		sc_bv<64>* dense_input_input_numel_tvin_wrapc_buffer = new sc_bv<64>[1];

		// RTL Name: dense_input_input_numel
		{
			// bitslice(63, 0)
			{
				int hls_map_index = 0;
				// celement: dense_input_input_.numel(63, 0)
				{
					// carray: (0) => (0) @ (1)
					for (int i_0 = 0; i_0 <= 0; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : dense_input_input_->numel
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : dense_input_input_->numel
						// regulate_c_name       : dense_input_input__numel
						// input_type_conversion : dense_input_input_->numel
						if (&(dense_input_input_->numel) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<64> dense_input_input__numel_tmp_mem;
							dense_input_input__numel_tmp_mem = dense_input_input_->numel;
							dense_input_input_numel_tvin_wrapc_buffer[hls_map_index].range(63, 0) = dense_input_input__numel_tmp_mem.range(63, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_dense_input_input_numel, "%s\n", (dense_input_input_numel_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_dense_input_input_numel, tvin_dense_input_input_numel);
		}

		tcl_file.set_num(1, &tcl_file.dense_input_input_numel_depth);
		sprintf(tvin_dense_input_input_numel, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_dense_input_input_numel, tvin_dense_input_input_numel);

		// release memory allocation
		delete [] dense_input_input_numel_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_dense_input_input_shape, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_dense_input_input_shape, tvin_dense_input_input_shape);

		sc_bv<64>* dense_input_input_shape_tvin_wrapc_buffer = new sc_bv<64>[5];

		// RTL Name: dense_input_input_shape
		{
			// bitslice(63, 0)
			{
				int hls_map_index = 0;
				// celement: dense_input_input_.shape(63, 0)
				{
					// carray: (0) => (4) @ (1)
					for (int i_0 = 0; i_0 <= 4; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : dense_input_input_->shape[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : dense_input_input_->shape[0]
						// regulate_c_name       : dense_input_input__shape
						// input_type_conversion : dense_input_input_->shape[i_0]
						if (&(dense_input_input_->shape[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<64> dense_input_input__shape_tmp_mem;
							dense_input_input__shape_tmp_mem = dense_input_input_->shape[i_0];
							dense_input_input_shape_tvin_wrapc_buffer[hls_map_index].range(63, 0) = dense_input_input__shape_tmp_mem.range(63, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 5; i++)
		{
			sprintf(tvin_dense_input_input_shape, "%s\n", (dense_input_input_shape_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_dense_input_input_shape, tvin_dense_input_input_shape);
		}

		tcl_file.set_num(5, &tcl_file.dense_input_input_shape_depth);
		sprintf(tvin_dense_input_input_shape, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_dense_input_input_shape, tvin_dense_input_input_shape);

		// release memory allocation
		delete [] dense_input_input_shape_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_dense_3_output_array, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_dense_3_output_array, tvin_dense_3_output_array);

		sc_bv<32>* dense_3_output_array_tvin_wrapc_buffer = new sc_bv<32>[784];

		// RTL Name: dense_3_output_array
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: dense_3_output_.array(31, 0)
				{
					// carray: (0) => (783) @ (1)
					for (int i_0 = 0; i_0 <= 783; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : dense_3_output_->array[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : dense_3_output_->array[0]
						// regulate_c_name       : dense_3_output__array
						// input_type_conversion : *(int*)&dense_3_output_->array[i_0]
						if (&(dense_3_output_->array[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> dense_3_output__array_tmp_mem;
							dense_3_output__array_tmp_mem = *(int*)&dense_3_output_->array[i_0];
							dense_3_output_array_tvin_wrapc_buffer[hls_map_index].range(31, 0) = dense_3_output__array_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 784; i++)
		{
			sprintf(tvin_dense_3_output_array, "%s\n", (dense_3_output_array_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_dense_3_output_array, tvin_dense_3_output_array);
		}

		tcl_file.set_num(784, &tcl_file.dense_3_output_array_depth);
		sprintf(tvin_dense_3_output_array, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_dense_3_output_array, tvin_dense_3_output_array);

		// release memory allocation
		delete [] dense_3_output_array_tvin_wrapc_buffer;

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		vlsiModel(dense_input_input_, dense_3_output_);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_dense_3_output_array, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_dense_3_output_array, tvout_dense_3_output_array);

		sc_bv<32>* dense_3_output_array_tvout_wrapc_buffer = new sc_bv<32>[784];

		// RTL Name: dense_3_output_array
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: dense_3_output_.array(31, 0)
				{
					// carray: (0) => (783) @ (1)
					for (int i_0 = 0; i_0 <= 783; i_0 += 1)
					{
						// sub                   : i_0
						// ori_name              : dense_3_output_->array[i_0]
						// sub_1st_elem          : 0
						// ori_name_1st_elem     : dense_3_output_->array[0]
						// regulate_c_name       : dense_3_output__array
						// input_type_conversion : *(int*)&dense_3_output_->array[i_0]
						if (&(dense_3_output_->array[0]) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> dense_3_output__array_tmp_mem;
							dense_3_output__array_tmp_mem = *(int*)&dense_3_output_->array[i_0];
							dense_3_output_array_tvout_wrapc_buffer[hls_map_index].range(31, 0) = dense_3_output__array_tmp_mem.range(31, 0);
                                 	       hls_map_index++;
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 784; i++)
		{
			sprintf(tvout_dense_3_output_array, "%s\n", (dense_3_output_array_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_dense_3_output_array, tvout_dense_3_output_array);
		}

		tcl_file.set_num(784, &tcl_file.dense_3_output_array_depth);
		sprintf(tvout_dense_3_output_array, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_dense_3_output_array, tvout_dense_3_output_array);

		// release memory allocation
		delete [] dense_3_output_array_tvout_wrapc_buffer;

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "dense_input_input_array"
		delete [] tvin_dense_input_input_array;
		// release memory allocation: "dense_input_input_ndim"
		delete [] tvin_dense_input_input_ndim;
		// release memory allocation: "dense_input_input_numel"
		delete [] tvin_dense_input_input_numel;
		// release memory allocation: "dense_input_input_shape"
		delete [] tvin_dense_input_input_shape;
		// release memory allocation: "dense_3_output_array"
		delete [] tvout_dense_3_output_array;
		delete [] tvin_dense_3_output_array;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);
	}
}

