// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="vlsiModel,hls_ip_2018_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200tfbg676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.122000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=870,HLS_SYN_DSP=329,HLS_SYN_FF=49842,HLS_SYN_LUT=41974,HLS_VERSION=2018_2}" *)

module vlsiModel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        dense_input_input_array_address0,
        dense_input_input_array_ce0,
        dense_input_input_array_q0,
        dense_input_input_ndim,
        dense_input_input_numel,
        dense_input_input_shape_address0,
        dense_input_input_shape_ce0,
        dense_input_input_shape_q0,
        dense_input_input_shape_address1,
        dense_input_input_shape_ce1,
        dense_input_input_shape_q1,
        dense_3_output_array_address0,
        dense_3_output_array_ce0,
        dense_3_output_array_we0,
        dense_3_output_array_d0,
        dense_3_output_ndim,
        dense_3_output_numel,
        dense_3_output_shape_address0,
        dense_3_output_shape_ce0,
        dense_3_output_shape_we0,
        dense_3_output_shape_d0,
        dense_3_output_shape_q0,
        dense_3_output_shape_address1,
        dense_3_output_shape_ce1,
        dense_3_output_shape_we1,
        dense_3_output_shape_d1,
        dense_3_output_shape_q1
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] dense_input_input_array_address0;
output   dense_input_input_array_ce0;
input  [31:0] dense_input_input_array_q0;
input  [63:0] dense_input_input_ndim;
input  [63:0] dense_input_input_numel;
output  [2:0] dense_input_input_shape_address0;
output   dense_input_input_shape_ce0;
input  [63:0] dense_input_input_shape_q0;
output  [2:0] dense_input_input_shape_address1;
output   dense_input_input_shape_ce1;
input  [63:0] dense_input_input_shape_q1;
output  [9:0] dense_3_output_array_address0;
output   dense_3_output_array_ce0;
output   dense_3_output_array_we0;
output  [31:0] dense_3_output_array_d0;
input  [63:0] dense_3_output_ndim;
input  [63:0] dense_3_output_numel;
output  [2:0] dense_3_output_shape_address0;
output   dense_3_output_shape_ce0;
output   dense_3_output_shape_we0;
output  [63:0] dense_3_output_shape_d0;
input  [63:0] dense_3_output_shape_q0;
output  [2:0] dense_3_output_shape_address1;
output   dense_3_output_shape_ce1;
output   dense_3_output_shape_we1;
output  [63:0] dense_3_output_shape_d1;
input  [63:0] dense_3_output_shape_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg dense_input_input_array_ce0;
reg[2:0] dense_input_input_shape_address0;
reg dense_input_input_shape_ce0;
reg[2:0] dense_input_input_shape_address1;
reg dense_input_input_shape_ce1;
reg dense_3_output_array_ce0;
reg dense_3_output_array_we0;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [9:0] dense_input_input_ar_address0;
reg    dense_input_input_ar_ce0;
reg    dense_input_input_ar_we0;
wire   [31:0] dense_input_input_ar_q0;
reg   [63:0] dense_output_ndim;
reg   [63:0] dense_output_numel;
reg   [63:0] dense_1_output_ndim;
reg   [63:0] dense_1_output_numel;
reg   [63:0] dense_1_kernel_ndim;
reg   [63:0] dense_1_kernel_numel;
reg   [63:0] dense_1_bias_numel;
reg   [63:0] dense_2_output_ndim;
reg   [63:0] dense_2_output_numel;
reg   [63:0] dense_2_kernel_ndim;
reg   [63:0] dense_2_kernel_numel;
reg   [63:0] dense_2_bias_numel;
reg   [63:0] dense_3_kernel_ndim;
reg   [63:0] dense_3_kernel_numel;
reg   [63:0] dense_3_bias_numel;
reg   [6:0] dense_output_array_address0;
reg    dense_output_array_ce0;
reg    dense_output_array_we0;
wire   [31:0] dense_output_array_q0;
reg   [2:0] dense_input_input_sh_address0;
reg    dense_input_input_sh_ce0;
reg    dense_input_input_sh_we0;
wire   [63:0] dense_input_input_sh_q0;
reg   [2:0] dense_input_input_sh_address1;
reg    dense_input_input_sh_ce1;
reg    dense_input_input_sh_we1;
reg   [2:0] dense_kernel_shape_address0;
reg    dense_kernel_shape_ce0;
reg    dense_kernel_shape_we0;
reg   [63:0] dense_kernel_shape_d0;
wire   [63:0] dense_kernel_shape_q0;
reg   [2:0] dense_kernel_shape_address1;
reg    dense_kernel_shape_ce1;
reg    dense_kernel_shape_we1;
reg   [5:0] dense_1_output_array_address0;
reg    dense_1_output_array_ce0;
reg    dense_1_output_array_we0;
wire   [31:0] dense_1_output_array_q0;
reg   [2:0] dense_output_shape_address0;
reg    dense_output_shape_ce0;
reg    dense_output_shape_we0;
reg   [63:0] dense_output_shape_d0;
wire   [63:0] dense_output_shape_q0;
reg   [2:0] dense_output_shape_address1;
reg    dense_output_shape_ce1;
reg    dense_output_shape_we1;
reg   [2:0] dense_1_kernel_shape_address0;
reg    dense_1_kernel_shape_ce0;
reg    dense_1_kernel_shape_we0;
reg   [63:0] dense_1_kernel_shape_d0;
wire   [63:0] dense_1_kernel_shape_q0;
reg   [2:0] dense_1_kernel_shape_address1;
reg    dense_1_kernel_shape_ce1;
reg    dense_1_kernel_shape_we1;
reg   [4:0] dense_2_output_array_address0;
reg    dense_2_output_array_ce0;
reg    dense_2_output_array_we0;
wire   [31:0] dense_2_output_array_q0;
reg   [2:0] dense_1_output_shape_address0;
reg    dense_1_output_shape_ce0;
reg    dense_1_output_shape_we0;
reg   [63:0] dense_1_output_shape_d0;
wire   [63:0] dense_1_output_shape_q0;
reg   [2:0] dense_1_output_shape_address1;
reg    dense_1_output_shape_ce1;
reg    dense_1_output_shape_we1;
reg   [2:0] dense_2_kernel_shape_address0;
reg    dense_2_kernel_shape_ce0;
reg    dense_2_kernel_shape_we0;
reg   [63:0] dense_2_kernel_shape_d0;
wire   [63:0] dense_2_kernel_shape_q0;
reg   [2:0] dense_2_kernel_shape_address1;
reg    dense_2_kernel_shape_ce1;
reg    dense_2_kernel_shape_we1;
reg   [2:0] dense_2_output_shape_address0;
reg    dense_2_output_shape_ce0;
reg    dense_2_output_shape_we0;
reg   [63:0] dense_2_output_shape_d0;
wire   [63:0] dense_2_output_shape_q0;
reg   [2:0] dense_2_output_shape_address1;
reg    dense_2_output_shape_ce1;
reg    dense_2_output_shape_we1;
reg   [2:0] dense_3_kernel_shape_address0;
reg    dense_3_kernel_shape_ce0;
reg    dense_3_kernel_shape_we0;
reg   [63:0] dense_3_kernel_shape_d0;
wire   [63:0] dense_3_kernel_shape_q0;
reg   [2:0] dense_3_kernel_shape_address1;
reg    dense_3_kernel_shape_ce1;
reg    dense_3_kernel_shape_we1;
reg   [3:0] dense_3_output_array_r_address0;
reg    dense_3_output_array_r_ce0;
reg    dense_3_output_array_r_we0;
wire   [31:0] dense_3_output_array_r_q0;
reg   [63:0] reg_622;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state11;
reg   [63:0] reg_628;
wire    ap_CS_fsm_state13;
wire   [63:0] z1_cast2_fu_634_p1;
reg   [63:0] z1_cast2_reg_823;
wire    ap_CS_fsm_state2;
wire   [9:0] z1_1_fu_645_p2;
reg   [9:0] z1_1_reg_831;
wire   [0:0] tmp_fu_639_p2;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state7;
wire   [63:0] z2_cast1_fu_806_p1;
reg   [63:0] z2_cast1_reg_941;
wire    ap_CS_fsm_state15;
wire   [3:0] z2_1_fu_817_p2;
reg   [3:0] z2_1_reg_949;
wire   [0:0] tmp_2_fu_811_p2;
wire    grp_k2c_dense_1_fu_515_ap_start;
wire    grp_k2c_dense_1_fu_515_ap_done;
wire    grp_k2c_dense_1_fu_515_ap_idle;
wire    grp_k2c_dense_1_fu_515_ap_ready;
wire   [2:0] grp_k2c_dense_1_fu_515_input_shape_address0;
wire    grp_k2c_dense_1_fu_515_input_shape_ce0;
wire   [2:0] grp_k2c_dense_1_fu_515_kernel_shape_address0;
wire    grp_k2c_dense_1_fu_515_kernel_shape_ce0;
wire   [3:0] grp_k2c_dense_1_fu_515_output_array_address0;
wire    grp_k2c_dense_1_fu_515_output_array_ce0;
wire    grp_k2c_dense_1_fu_515_output_array_we0;
wire   [31:0] grp_k2c_dense_1_fu_515_output_array_d0;
wire   [4:0] grp_k2c_dense_1_fu_515_dense_2_output_array_address0;
wire    grp_k2c_dense_1_fu_515_dense_2_output_array_ce0;
wire    grp_k2c_dense_3_fu_540_ap_start;
wire    grp_k2c_dense_3_fu_540_ap_done;
wire    grp_k2c_dense_3_fu_540_ap_idle;
wire    grp_k2c_dense_3_fu_540_ap_ready;
wire   [2:0] grp_k2c_dense_3_fu_540_input_shape_address0;
wire    grp_k2c_dense_3_fu_540_input_shape_ce0;
wire   [2:0] grp_k2c_dense_3_fu_540_kernel_shape_address0;
wire    grp_k2c_dense_3_fu_540_kernel_shape_ce0;
wire   [5:0] grp_k2c_dense_3_fu_540_dense_1_output_array_address0;
wire    grp_k2c_dense_3_fu_540_dense_1_output_array_ce0;
wire    grp_k2c_dense_3_fu_540_dense_1_output_array_we0;
wire   [31:0] grp_k2c_dense_3_fu_540_dense_1_output_array_d0;
wire   [6:0] grp_k2c_dense_3_fu_540_dense_output_array_address0;
wire    grp_k2c_dense_3_fu_540_dense_output_array_ce0;
wire    grp_k2c_dense_2_fu_564_ap_start;
wire    grp_k2c_dense_2_fu_564_ap_done;
wire    grp_k2c_dense_2_fu_564_ap_idle;
wire    grp_k2c_dense_2_fu_564_ap_ready;
wire   [2:0] grp_k2c_dense_2_fu_564_input_shape_address0;
wire    grp_k2c_dense_2_fu_564_input_shape_ce0;
wire   [2:0] grp_k2c_dense_2_fu_564_kernel_shape_address0;
wire    grp_k2c_dense_2_fu_564_kernel_shape_ce0;
wire   [4:0] grp_k2c_dense_2_fu_564_dense_2_output_array_address0;
wire    grp_k2c_dense_2_fu_564_dense_2_output_array_ce0;
wire    grp_k2c_dense_2_fu_564_dense_2_output_array_we0;
wire   [31:0] grp_k2c_dense_2_fu_564_dense_2_output_array_d0;
wire   [5:0] grp_k2c_dense_2_fu_564_dense_1_output_array_address0;
wire    grp_k2c_dense_2_fu_564_dense_1_output_array_ce0;
wire    grp_k2c_dense_fu_588_ap_start;
wire    grp_k2c_dense_fu_588_ap_done;
wire    grp_k2c_dense_fu_588_ap_idle;
wire    grp_k2c_dense_fu_588_ap_ready;
wire   [2:0] grp_k2c_dense_fu_588_input_shape_address0;
wire    grp_k2c_dense_fu_588_input_shape_ce0;
wire   [2:0] grp_k2c_dense_fu_588_kernel_shape_address0;
wire    grp_k2c_dense_fu_588_kernel_shape_ce0;
wire   [9:0] grp_k2c_dense_fu_588_input_array_address0;
wire    grp_k2c_dense_fu_588_input_array_ce0;
wire   [6:0] grp_k2c_dense_fu_588_dense_output_array_address0;
wire    grp_k2c_dense_fu_588_dense_output_array_ce0;
wire    grp_k2c_dense_fu_588_dense_output_array_we0;
wire   [31:0] grp_k2c_dense_fu_588_dense_output_array_d0;
reg   [9:0] z1_reg_493;
wire    ap_CS_fsm_state3;
reg   [3:0] z2_reg_504;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state16;
reg    grp_k2c_dense_1_fu_515_ap_start_reg;
reg    grp_k2c_dense_3_fu_540_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    grp_k2c_dense_2_fu_564_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_k2c_dense_fu_588_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state6;
reg   [15:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 dense_output_ndim = 64'd0;
#0 dense_output_numel = 64'd0;
#0 dense_1_output_ndim = 64'd0;
#0 dense_1_output_numel = 64'd0;
#0 dense_1_kernel_ndim = 64'd0;
#0 dense_1_kernel_numel = 64'd0;
#0 dense_1_bias_numel = 64'd0;
#0 dense_2_output_ndim = 64'd0;
#0 dense_2_output_numel = 64'd0;
#0 dense_2_kernel_ndim = 64'd0;
#0 dense_2_kernel_numel = 64'd0;
#0 dense_2_bias_numel = 64'd0;
#0 dense_3_kernel_ndim = 64'd0;
#0 dense_3_kernel_numel = 64'd0;
#0 dense_3_bias_numel = 64'd0;
#0 grp_k2c_dense_1_fu_515_ap_start_reg = 1'b0;
#0 grp_k2c_dense_3_fu_540_ap_start_reg = 1'b0;
#0 grp_k2c_dense_2_fu_564_ap_start_reg = 1'b0;
#0 grp_k2c_dense_fu_588_ap_start_reg = 1'b0;
end

vlsiModel_dense_iLf8 #(
    .DataWidth( 32 ),
    .AddressRange( 784 ),
    .AddressWidth( 10 ))
dense_input_input_ar_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_input_input_ar_address0),
    .ce0(dense_input_input_ar_ce0),
    .we0(dense_input_input_ar_we0),
    .d0(dense_input_input_array_q0),
    .q0(dense_input_input_ar_q0)
);

vlsiModel_dense_oMgi #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
dense_output_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_output_array_address0),
    .ce0(dense_output_array_ce0),
    .we0(dense_output_array_we0),
    .d0(grp_k2c_dense_fu_588_dense_output_array_d0),
    .q0(dense_output_array_q0)
);

vlsiModel_dense_iNgs #(
    .DataWidth( 64 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
dense_input_input_sh_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_input_input_sh_address0),
    .ce0(dense_input_input_sh_ce0),
    .we0(dense_input_input_sh_we0),
    .d0(dense_input_input_shape_q0),
    .q0(dense_input_input_sh_q0),
    .address1(dense_input_input_sh_address1),
    .ce1(dense_input_input_sh_ce1),
    .we1(dense_input_input_sh_we1),
    .d1(dense_input_input_shape_q1)
);

vlsiModel_dense_iNgs #(
    .DataWidth( 64 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
dense_kernel_shape_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_kernel_shape_address0),
    .ce0(dense_kernel_shape_ce0),
    .we0(dense_kernel_shape_we0),
    .d0(dense_kernel_shape_d0),
    .q0(dense_kernel_shape_q0),
    .address1(dense_kernel_shape_address1),
    .ce1(dense_kernel_shape_ce1),
    .we1(dense_kernel_shape_we1),
    .d1(64'd1)
);

vlsiModel_dense_1PgM #(
    .DataWidth( 32 ),
    .AddressRange( 50 ),
    .AddressWidth( 6 ))
dense_1_output_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_1_output_array_address0),
    .ce0(dense_1_output_array_ce0),
    .we0(dense_1_output_array_we0),
    .d0(grp_k2c_dense_3_fu_540_dense_1_output_array_d0),
    .q0(dense_1_output_array_q0)
);

vlsiModel_dense_iNgs #(
    .DataWidth( 64 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
dense_output_shape_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_output_shape_address0),
    .ce0(dense_output_shape_ce0),
    .we0(dense_output_shape_we0),
    .d0(dense_output_shape_d0),
    .q0(dense_output_shape_q0),
    .address1(dense_output_shape_address1),
    .ce1(dense_output_shape_ce1),
    .we1(dense_output_shape_we1),
    .d1(64'd1)
);

vlsiModel_dense_iNgs #(
    .DataWidth( 64 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
dense_1_kernel_shape_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_1_kernel_shape_address0),
    .ce0(dense_1_kernel_shape_ce0),
    .we0(dense_1_kernel_shape_we0),
    .d0(dense_1_kernel_shape_d0),
    .q0(dense_1_kernel_shape_q0),
    .address1(dense_1_kernel_shape_address1),
    .ce1(dense_1_kernel_shape_ce1),
    .we1(dense_1_kernel_shape_we1),
    .d1(64'd1)
);

vlsiModel_dense_2Shg #(
    .DataWidth( 32 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
dense_2_output_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_2_output_array_address0),
    .ce0(dense_2_output_array_ce0),
    .we0(dense_2_output_array_we0),
    .d0(grp_k2c_dense_2_fu_564_dense_2_output_array_d0),
    .q0(dense_2_output_array_q0)
);

vlsiModel_dense_iNgs #(
    .DataWidth( 64 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
dense_1_output_shape_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_1_output_shape_address0),
    .ce0(dense_1_output_shape_ce0),
    .we0(dense_1_output_shape_we0),
    .d0(dense_1_output_shape_d0),
    .q0(dense_1_output_shape_q0),
    .address1(dense_1_output_shape_address1),
    .ce1(dense_1_output_shape_ce1),
    .we1(dense_1_output_shape_we1),
    .d1(64'd1)
);

vlsiModel_dense_iNgs #(
    .DataWidth( 64 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
dense_2_kernel_shape_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_2_kernel_shape_address0),
    .ce0(dense_2_kernel_shape_ce0),
    .we0(dense_2_kernel_shape_we0),
    .d0(dense_2_kernel_shape_d0),
    .q0(dense_2_kernel_shape_q0),
    .address1(dense_2_kernel_shape_address1),
    .ce1(dense_2_kernel_shape_ce1),
    .we1(dense_2_kernel_shape_we1),
    .d1(64'd1)
);

vlsiModel_dense_iNgs #(
    .DataWidth( 64 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
dense_2_output_shape_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_2_output_shape_address0),
    .ce0(dense_2_output_shape_ce0),
    .we0(dense_2_output_shape_we0),
    .d0(dense_2_output_shape_d0),
    .q0(dense_2_output_shape_q0),
    .address1(dense_2_output_shape_address1),
    .ce1(dense_2_output_shape_ce1),
    .we1(dense_2_output_shape_we1),
    .d1(64'd1)
);

vlsiModel_dense_iNgs #(
    .DataWidth( 64 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
dense_3_kernel_shape_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_3_kernel_shape_address0),
    .ce0(dense_3_kernel_shape_ce0),
    .we0(dense_3_kernel_shape_we0),
    .d0(dense_3_kernel_shape_d0),
    .q0(dense_3_kernel_shape_q0),
    .address1(dense_3_kernel_shape_address1),
    .ce1(dense_3_kernel_shape_ce1),
    .we1(dense_3_kernel_shape_we1),
    .d1(64'd1)
);

vlsiModel_dense_3Xh4 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
dense_3_output_array_r_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense_3_output_array_r_address0),
    .ce0(dense_3_output_array_r_ce0),
    .we0(dense_3_output_array_r_we0),
    .d0(grp_k2c_dense_1_fu_515_output_array_d0),
    .q0(dense_3_output_array_r_q0)
);

k2c_dense_1 grp_k2c_dense_1_fu_515(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_k2c_dense_1_fu_515_ap_start),
    .ap_done(grp_k2c_dense_1_fu_515_ap_done),
    .ap_idle(grp_k2c_dense_1_fu_515_ap_idle),
    .ap_ready(grp_k2c_dense_1_fu_515_ap_ready),
    .input_ndim_read(dense_2_output_ndim),
    .input_numel_read(reg_628),
    .input_shape_address0(grp_k2c_dense_1_fu_515_input_shape_address0),
    .input_shape_ce0(grp_k2c_dense_1_fu_515_input_shape_ce0),
    .input_shape_q0(dense_2_output_shape_q0),
    .kernel_ndim_read(dense_3_kernel_ndim),
    .kernel_numel_read(dense_3_kernel_numel),
    .kernel_shape_address0(grp_k2c_dense_1_fu_515_kernel_shape_address0),
    .kernel_shape_ce0(grp_k2c_dense_1_fu_515_kernel_shape_ce0),
    .kernel_shape_q0(dense_3_kernel_shape_q0),
    .bias_numel_read(dense_3_bias_numel),
    .output_array_address0(grp_k2c_dense_1_fu_515_output_array_address0),
    .output_array_ce0(grp_k2c_dense_1_fu_515_output_array_ce0),
    .output_array_we0(grp_k2c_dense_1_fu_515_output_array_we0),
    .output_array_d0(grp_k2c_dense_1_fu_515_output_array_d0),
    .output_array_q0(dense_3_output_array_r_q0),
    .dense_2_output_array_address0(grp_k2c_dense_1_fu_515_dense_2_output_array_address0),
    .dense_2_output_array_ce0(grp_k2c_dense_1_fu_515_dense_2_output_array_ce0),
    .dense_2_output_array_q0(dense_2_output_array_q0)
);

k2c_dense_3 grp_k2c_dense_3_fu_540(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_k2c_dense_3_fu_540_ap_start),
    .ap_done(grp_k2c_dense_3_fu_540_ap_done),
    .ap_idle(grp_k2c_dense_3_fu_540_ap_idle),
    .ap_ready(grp_k2c_dense_3_fu_540_ap_ready),
    .output_numel_read(reg_622),
    .input_ndim_read(dense_output_ndim),
    .input_numel_read(dense_output_numel),
    .input_shape_address0(grp_k2c_dense_3_fu_540_input_shape_address0),
    .input_shape_ce0(grp_k2c_dense_3_fu_540_input_shape_ce0),
    .input_shape_q0(dense_output_shape_q0),
    .kernel_ndim_read(dense_1_kernel_ndim),
    .kernel_numel_read(dense_1_kernel_numel),
    .kernel_shape_address0(grp_k2c_dense_3_fu_540_kernel_shape_address0),
    .kernel_shape_ce0(grp_k2c_dense_3_fu_540_kernel_shape_ce0),
    .kernel_shape_q0(dense_1_kernel_shape_q0),
    .bias_numel_read(dense_1_bias_numel),
    .dense_1_output_array_address0(grp_k2c_dense_3_fu_540_dense_1_output_array_address0),
    .dense_1_output_array_ce0(grp_k2c_dense_3_fu_540_dense_1_output_array_ce0),
    .dense_1_output_array_we0(grp_k2c_dense_3_fu_540_dense_1_output_array_we0),
    .dense_1_output_array_d0(grp_k2c_dense_3_fu_540_dense_1_output_array_d0),
    .dense_1_output_array_q0(dense_1_output_array_q0),
    .dense_output_array_address0(grp_k2c_dense_3_fu_540_dense_output_array_address0),
    .dense_output_array_ce0(grp_k2c_dense_3_fu_540_dense_output_array_ce0),
    .dense_output_array_q0(dense_output_array_q0)
);

k2c_dense_2 grp_k2c_dense_2_fu_564(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_k2c_dense_2_fu_564_ap_start),
    .ap_done(grp_k2c_dense_2_fu_564_ap_done),
    .ap_idle(grp_k2c_dense_2_fu_564_ap_idle),
    .ap_ready(grp_k2c_dense_2_fu_564_ap_ready),
    .output_numel_read(reg_628),
    .input_ndim_read(dense_1_output_ndim),
    .input_numel_read(reg_622),
    .input_shape_address0(grp_k2c_dense_2_fu_564_input_shape_address0),
    .input_shape_ce0(grp_k2c_dense_2_fu_564_input_shape_ce0),
    .input_shape_q0(dense_1_output_shape_q0),
    .kernel_ndim_read(dense_2_kernel_ndim),
    .kernel_numel_read(dense_2_kernel_numel),
    .kernel_shape_address0(grp_k2c_dense_2_fu_564_kernel_shape_address0),
    .kernel_shape_ce0(grp_k2c_dense_2_fu_564_kernel_shape_ce0),
    .kernel_shape_q0(dense_2_kernel_shape_q0),
    .bias_numel_read(dense_2_bias_numel),
    .dense_2_output_array_address0(grp_k2c_dense_2_fu_564_dense_2_output_array_address0),
    .dense_2_output_array_ce0(grp_k2c_dense_2_fu_564_dense_2_output_array_ce0),
    .dense_2_output_array_we0(grp_k2c_dense_2_fu_564_dense_2_output_array_we0),
    .dense_2_output_array_d0(grp_k2c_dense_2_fu_564_dense_2_output_array_d0),
    .dense_2_output_array_q0(dense_2_output_array_q0),
    .dense_1_output_array_address0(grp_k2c_dense_2_fu_564_dense_1_output_array_address0),
    .dense_1_output_array_ce0(grp_k2c_dense_2_fu_564_dense_1_output_array_ce0),
    .dense_1_output_array_q0(dense_1_output_array_q0)
);

k2c_dense grp_k2c_dense_fu_588(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_k2c_dense_fu_588_ap_start),
    .ap_done(grp_k2c_dense_fu_588_ap_done),
    .ap_idle(grp_k2c_dense_fu_588_ap_idle),
    .ap_ready(grp_k2c_dense_fu_588_ap_ready),
    .input_ndim_read(dense_input_input_ndim),
    .input_numel_read(dense_input_input_numel),
    .input_shape_address0(grp_k2c_dense_fu_588_input_shape_address0),
    .input_shape_ce0(grp_k2c_dense_fu_588_input_shape_ce0),
    .input_shape_q0(dense_input_input_sh_q0),
    .kernel_shape_address0(grp_k2c_dense_fu_588_kernel_shape_address0),
    .kernel_shape_ce0(grp_k2c_dense_fu_588_kernel_shape_ce0),
    .kernel_shape_q0(dense_kernel_shape_q0),
    .input_array_address0(grp_k2c_dense_fu_588_input_array_address0),
    .input_array_ce0(grp_k2c_dense_fu_588_input_array_ce0),
    .input_array_q0(dense_input_input_ar_q0),
    .dense_output_array_address0(grp_k2c_dense_fu_588_dense_output_array_address0),
    .dense_output_array_ce0(grp_k2c_dense_fu_588_dense_output_array_ce0),
    .dense_output_array_we0(grp_k2c_dense_fu_588_dense_output_array_we0),
    .dense_output_array_d0(grp_k2c_dense_fu_588_dense_output_array_d0),
    .dense_output_array_q0(dense_output_array_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_k2c_dense_1_fu_515_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_k2c_dense_1_fu_515_ap_start_reg <= 1'b1;
        end else if ((grp_k2c_dense_1_fu_515_ap_ready == 1'b1)) begin
            grp_k2c_dense_1_fu_515_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_k2c_dense_2_fu_564_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_k2c_dense_2_fu_564_ap_start_reg <= 1'b1;
        end else if ((grp_k2c_dense_2_fu_564_ap_ready == 1'b1)) begin
            grp_k2c_dense_2_fu_564_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_k2c_dense_3_fu_540_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_k2c_dense_3_fu_540_ap_start_reg <= 1'b1;
        end else if ((grp_k2c_dense_3_fu_540_ap_ready == 1'b1)) begin
            grp_k2c_dense_3_fu_540_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_k2c_dense_fu_588_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_k2c_dense_fu_588_ap_start_reg <= 1'b1;
        end else if ((grp_k2c_dense_fu_588_ap_ready == 1'b1)) begin
            grp_k2c_dense_fu_588_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        z1_reg_493 <= z1_1_reg_831;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        z1_reg_493 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        z2_reg_504 <= z2_1_reg_949;
    end else if (((grp_k2c_dense_1_fu_515_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        z2_reg_504 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_639_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        dense_1_bias_numel[1] <= 1'b1;
dense_1_bias_numel[4] <= 1'b1;
dense_1_bias_numel[5] <= 1'b1;
        dense_1_kernel_ndim[1] <= 1'b1;
        dense_1_kernel_numel[3] <= 1'b1;
dense_1_kernel_numel[7] <= 1'b1;
dense_1_kernel_numel[8] <= 1'b1;
dense_1_kernel_numel[9] <= 1'b1;
dense_1_kernel_numel[12] <= 1'b1;
        dense_1_output_ndim[0] <= 1'b1;
        dense_1_output_numel[1] <= 1'b1;
dense_1_output_numel[4] <= 1'b1;
dense_1_output_numel[5] <= 1'b1;
        dense_2_bias_numel[0] <= 1'b1;
dense_2_bias_numel[3] <= 1'b1;
dense_2_bias_numel[4] <= 1'b1;
        dense_2_kernel_ndim[1] <= 1'b1;
        dense_2_kernel_numel[1] <= 1'b1;
dense_2_kernel_numel[5] <= 1'b1;
dense_2_kernel_numel[6] <= 1'b1;
dense_2_kernel_numel[7] <= 1'b1;
dense_2_kernel_numel[10] <= 1'b1;
        dense_2_output_ndim[0] <= 1'b1;
        dense_2_output_numel[0] <= 1'b1;
dense_2_output_numel[3] <= 1'b1;
dense_2_output_numel[4] <= 1'b1;
        dense_3_bias_numel[1] <= 1'b1;
dense_3_bias_numel[3] <= 1'b1;
        dense_3_kernel_ndim[1] <= 1'b1;
        dense_3_kernel_numel[1] <= 1'b1;
dense_3_kernel_numel[3] <= 1'b1;
dense_3_kernel_numel[4] <= 1'b1;
dense_3_kernel_numel[5] <= 1'b1;
dense_3_kernel_numel[6] <= 1'b1;
dense_3_kernel_numel[7] <= 1'b1;
        dense_output_ndim[0] <= 1'b1;
        dense_output_numel[2] <= 1'b1;
dense_output_numel[5] <= 1'b1;
dense_output_numel[6] <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state9))) begin
        reg_622[1] <= dense_1_output_numel[1];
reg_622[5 : 4] <= dense_1_output_numel[5 : 4];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state11))) begin
        reg_628[0] <= dense_2_output_numel[0];
reg_628[4 : 3] <= dense_2_output_numel[4 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        z1_1_reg_831 <= z1_1_fu_645_p2;
        z1_cast2_reg_823[9 : 0] <= z1_cast2_fu_634_p1[9 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        z2_1_reg_949 <= z2_1_fu_817_p2;
        z2_cast1_reg_941[3 : 0] <= z2_cast1_fu_806_p1[3 : 0];
    end
end

always @ (*) begin
    if (((tmp_2_fu_811_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_fu_811_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_1_kernel_shape_address0 = 3'd4;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        dense_1_kernel_shape_address0 = 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        dense_1_kernel_shape_address0 = 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_1_kernel_shape_address0 = grp_k2c_dense_3_fu_540_kernel_shape_address0;
    end else begin
        dense_1_kernel_shape_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_1_kernel_shape_address1 = 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        dense_1_kernel_shape_address1 = 3'd2;
    end else begin
        dense_1_kernel_shape_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state7) | ((grp_k2c_dense_fu_588_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)))) begin
        dense_1_kernel_shape_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_1_kernel_shape_ce0 = grp_k2c_dense_3_fu_540_kernel_shape_ce0;
    end else begin
        dense_1_kernel_shape_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((grp_k2c_dense_fu_588_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)))) begin
        dense_1_kernel_shape_ce1 = 1'b1;
    end else begin
        dense_1_kernel_shape_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_1_kernel_shape_d0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        dense_1_kernel_shape_d0 = 64'd50;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        dense_1_kernel_shape_d0 = 64'd100;
    end else begin
        dense_1_kernel_shape_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state7) | ((grp_k2c_dense_fu_588_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)))) begin
        dense_1_kernel_shape_we0 = 1'b1;
    end else begin
        dense_1_kernel_shape_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((grp_k2c_dense_fu_588_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)))) begin
        dense_1_kernel_shape_we1 = 1'b1;
    end else begin
        dense_1_kernel_shape_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_1_output_array_address0 = grp_k2c_dense_2_fu_564_dense_1_output_array_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_1_output_array_address0 = grp_k2c_dense_3_fu_540_dense_1_output_array_address0;
    end else begin
        dense_1_output_array_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_1_output_array_ce0 = grp_k2c_dense_2_fu_564_dense_1_output_array_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_1_output_array_ce0 = grp_k2c_dense_3_fu_540_dense_1_output_array_ce0;
    end else begin
        dense_1_output_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_1_output_array_we0 = grp_k2c_dense_3_fu_540_dense_1_output_array_we0;
    end else begin
        dense_1_output_array_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_1_output_shape_address0 = 3'd4;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dense_1_output_shape_address0 = 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_1_output_shape_address0 = 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_1_output_shape_address0 = grp_k2c_dense_2_fu_564_input_shape_address0;
    end else begin
        dense_1_output_shape_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_1_output_shape_address1 = 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dense_1_output_shape_address1 = 3'd2;
    end else begin
        dense_1_output_shape_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((grp_k2c_dense_fu_588_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((grp_k2c_dense_3_fu_540_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        dense_1_output_shape_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_1_output_shape_ce0 = grp_k2c_dense_2_fu_564_input_shape_ce0;
    end else begin
        dense_1_output_shape_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((grp_k2c_dense_3_fu_540_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        dense_1_output_shape_ce1 = 1'b1;
    end else begin
        dense_1_output_shape_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9))) begin
        dense_1_output_shape_d0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_1_output_shape_d0 = 64'd50;
    end else begin
        dense_1_output_shape_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((grp_k2c_dense_fu_588_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((grp_k2c_dense_3_fu_540_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        dense_1_output_shape_we0 = 1'b1;
    end else begin
        dense_1_output_shape_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((grp_k2c_dense_3_fu_540_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        dense_1_output_shape_we1 = 1'b1;
    end else begin
        dense_1_output_shape_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_2_kernel_shape_address0 = 3'd4;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dense_2_kernel_shape_address0 = 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_2_kernel_shape_address0 = 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_2_kernel_shape_address0 = grp_k2c_dense_2_fu_564_kernel_shape_address0;
    end else begin
        dense_2_kernel_shape_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_2_kernel_shape_address1 = 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dense_2_kernel_shape_address1 = 3'd2;
    end else begin
        dense_2_kernel_shape_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((grp_k2c_dense_fu_588_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((grp_k2c_dense_3_fu_540_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        dense_2_kernel_shape_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_2_kernel_shape_ce0 = grp_k2c_dense_2_fu_564_kernel_shape_ce0;
    end else begin
        dense_2_kernel_shape_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((grp_k2c_dense_3_fu_540_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        dense_2_kernel_shape_ce1 = 1'b1;
    end else begin
        dense_2_kernel_shape_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_2_kernel_shape_d0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        dense_2_kernel_shape_d0 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_2_kernel_shape_d0 = 64'd50;
    end else begin
        dense_2_kernel_shape_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((grp_k2c_dense_fu_588_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)) | ((grp_k2c_dense_3_fu_540_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        dense_2_kernel_shape_we0 = 1'b1;
    end else begin
        dense_2_kernel_shape_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((grp_k2c_dense_3_fu_540_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        dense_2_kernel_shape_we1 = 1'b1;
    end else begin
        dense_2_kernel_shape_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_2_output_array_address0 = grp_k2c_dense_2_fu_564_dense_2_output_array_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dense_2_output_array_address0 = grp_k2c_dense_1_fu_515_dense_2_output_array_address0;
    end else begin
        dense_2_output_array_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_2_output_array_ce0 = grp_k2c_dense_2_fu_564_dense_2_output_array_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dense_2_output_array_ce0 = grp_k2c_dense_1_fu_515_dense_2_output_array_ce0;
    end else begin
        dense_2_output_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_2_output_array_we0 = grp_k2c_dense_2_fu_564_dense_2_output_array_we0;
    end else begin
        dense_2_output_array_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_2_output_shape_address0 = 3'd4;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_2_output_shape_address0 = 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_2_output_shape_address0 = 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dense_2_output_shape_address0 = grp_k2c_dense_1_fu_515_input_shape_address0;
    end else begin
        dense_2_output_shape_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_2_output_shape_address1 = 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_2_output_shape_address1 = 3'd2;
    end else begin
        dense_2_output_shape_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((grp_k2c_dense_2_fu_564_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((grp_k2c_dense_3_fu_540_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        dense_2_output_shape_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dense_2_output_shape_ce0 = grp_k2c_dense_1_fu_515_input_shape_ce0;
    end else begin
        dense_2_output_shape_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((grp_k2c_dense_2_fu_564_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        dense_2_output_shape_ce1 = 1'b1;
    end else begin
        dense_2_output_shape_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        dense_2_output_shape_d0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_2_output_shape_d0 = 64'd25;
    end else begin
        dense_2_output_shape_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((grp_k2c_dense_2_fu_564_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((grp_k2c_dense_3_fu_540_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        dense_2_output_shape_we0 = 1'b1;
    end else begin
        dense_2_output_shape_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((grp_k2c_dense_2_fu_564_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        dense_2_output_shape_we1 = 1'b1;
    end else begin
        dense_2_output_shape_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_3_kernel_shape_address0 = 3'd4;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_3_kernel_shape_address0 = 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_3_kernel_shape_address0 = 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dense_3_kernel_shape_address0 = grp_k2c_dense_1_fu_515_kernel_shape_address0;
    end else begin
        dense_3_kernel_shape_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_3_kernel_shape_address1 = 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_3_kernel_shape_address1 = 3'd2;
    end else begin
        dense_3_kernel_shape_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((grp_k2c_dense_2_fu_564_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((grp_k2c_dense_3_fu_540_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        dense_3_kernel_shape_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dense_3_kernel_shape_ce0 = grp_k2c_dense_1_fu_515_kernel_shape_ce0;
    end else begin
        dense_3_kernel_shape_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((grp_k2c_dense_2_fu_564_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        dense_3_kernel_shape_ce1 = 1'b1;
    end else begin
        dense_3_kernel_shape_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        dense_3_kernel_shape_d0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        dense_3_kernel_shape_d0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_3_kernel_shape_d0 = 64'd25;
    end else begin
        dense_3_kernel_shape_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((grp_k2c_dense_2_fu_564_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((grp_k2c_dense_3_fu_540_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        dense_3_kernel_shape_we0 = 1'b1;
    end else begin
        dense_3_kernel_shape_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((grp_k2c_dense_2_fu_564_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12)))) begin
        dense_3_kernel_shape_we1 = 1'b1;
    end else begin
        dense_3_kernel_shape_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dense_3_output_array_ce0 = 1'b1;
    end else begin
        dense_3_output_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        dense_3_output_array_r_address0 = z2_cast1_fu_806_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dense_3_output_array_r_address0 = grp_k2c_dense_1_fu_515_output_array_address0;
    end else begin
        dense_3_output_array_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        dense_3_output_array_r_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        dense_3_output_array_r_ce0 = grp_k2c_dense_1_fu_515_output_array_ce0;
    end else begin
        dense_3_output_array_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        dense_3_output_array_r_we0 = grp_k2c_dense_1_fu_515_output_array_we0;
    end else begin
        dense_3_output_array_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        dense_3_output_array_we0 = 1'b1;
    end else begin
        dense_3_output_array_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        dense_input_input_ar_address0 = z1_cast2_reg_823;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_input_input_ar_address0 = grp_k2c_dense_fu_588_input_array_address0;
    end else begin
        dense_input_input_ar_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        dense_input_input_ar_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_input_input_ar_ce0 = grp_k2c_dense_fu_588_input_array_ce0;
    end else begin
        dense_input_input_ar_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        dense_input_input_ar_we0 = 1'b1;
    end else begin
        dense_input_input_ar_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_input_input_array_ce0 = 1'b1;
    end else begin
        dense_input_input_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        dense_input_input_sh_address0 = 3'd4;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_input_input_sh_address0 = 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_input_input_sh_address0 = 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_input_input_sh_address0 = grp_k2c_dense_fu_588_input_shape_address0;
    end else begin
        dense_input_input_sh_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        dense_input_input_sh_address1 = 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_input_input_sh_address1 = 3'd2;
    end else begin
        dense_input_input_sh_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        dense_input_input_sh_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_input_input_sh_ce0 = grp_k2c_dense_fu_588_input_shape_ce0;
    end else begin
        dense_input_input_sh_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        dense_input_input_sh_ce1 = 1'b1;
    end else begin
        dense_input_input_sh_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        dense_input_input_sh_we0 = 1'b1;
    end else begin
        dense_input_input_sh_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        dense_input_input_sh_we1 = 1'b1;
    end else begin
        dense_input_input_sh_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_input_input_shape_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_input_input_shape_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        dense_input_input_shape_address0 = 64'd0;
    end else begin
        dense_input_input_shape_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_input_input_shape_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_input_input_shape_address1 = 64'd2;
    end else begin
        dense_input_input_shape_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        dense_input_input_shape_ce0 = 1'b1;
    end else begin
        dense_input_input_shape_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        dense_input_input_shape_ce1 = 1'b1;
    end else begin
        dense_input_input_shape_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        dense_kernel_shape_address0 = 3'd4;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_kernel_shape_address0 = 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_kernel_shape_address0 = 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_kernel_shape_address0 = grp_k2c_dense_fu_588_kernel_shape_address0;
    end else begin
        dense_kernel_shape_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        dense_kernel_shape_address1 = 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_kernel_shape_address1 = 3'd2;
    end else begin
        dense_kernel_shape_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        dense_kernel_shape_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_kernel_shape_ce0 = grp_k2c_dense_fu_588_kernel_shape_ce0;
    end else begin
        dense_kernel_shape_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        dense_kernel_shape_ce1 = 1'b1;
    end else begin
        dense_kernel_shape_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        dense_kernel_shape_d0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dense_kernel_shape_d0 = 64'd100;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        dense_kernel_shape_d0 = 64'd784;
    end else begin
        dense_kernel_shape_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        dense_kernel_shape_we0 = 1'b1;
    end else begin
        dense_kernel_shape_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        dense_kernel_shape_we1 = 1'b1;
    end else begin
        dense_kernel_shape_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_output_array_address0 = grp_k2c_dense_fu_588_dense_output_array_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_output_array_address0 = grp_k2c_dense_3_fu_540_dense_output_array_address0;
    end else begin
        dense_output_array_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_output_array_ce0 = grp_k2c_dense_fu_588_dense_output_array_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_output_array_ce0 = grp_k2c_dense_3_fu_540_dense_output_array_ce0;
    end else begin
        dense_output_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_output_array_we0 = grp_k2c_dense_fu_588_dense_output_array_we0;
    end else begin
        dense_output_array_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_output_shape_address0 = 3'd4;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        dense_output_shape_address0 = 3'd1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        dense_output_shape_address0 = 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_output_shape_address0 = grp_k2c_dense_3_fu_540_input_shape_address0;
    end else begin
        dense_output_shape_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        dense_output_shape_address1 = 3'd3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        dense_output_shape_address1 = 3'd2;
    end else begin
        dense_output_shape_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state7) | ((grp_k2c_dense_fu_588_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)))) begin
        dense_output_shape_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        dense_output_shape_ce0 = grp_k2c_dense_3_fu_540_input_shape_ce0;
    end else begin
        dense_output_shape_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((grp_k2c_dense_fu_588_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)))) begin
        dense_output_shape_ce1 = 1'b1;
    end else begin
        dense_output_shape_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        dense_output_shape_d0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        dense_output_shape_d0 = 64'd100;
    end else begin
        dense_output_shape_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state7) | ((grp_k2c_dense_fu_588_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)))) begin
        dense_output_shape_we0 = 1'b1;
    end else begin
        dense_output_shape_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((grp_k2c_dense_fu_588_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8)))) begin
        dense_output_shape_we1 = 1'b1;
    end else begin
        dense_output_shape_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_fu_639_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_k2c_dense_fu_588_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_k2c_dense_3_fu_540_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_k2c_dense_2_fu_564_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_k2c_dense_1_fu_515_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((tmp_2_fu_811_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign dense_3_output_array_address0 = z2_cast1_reg_941;

assign dense_3_output_array_d0 = dense_3_output_array_r_q0;

assign dense_3_output_shape_address0 = 3'd0;

assign dense_3_output_shape_address1 = 3'd0;

assign dense_3_output_shape_ce0 = 1'b0;

assign dense_3_output_shape_ce1 = 1'b0;

assign dense_3_output_shape_d0 = 64'd0;

assign dense_3_output_shape_d1 = 64'd0;

assign dense_3_output_shape_we0 = 1'b0;

assign dense_3_output_shape_we1 = 1'b0;

assign dense_input_input_array_address0 = z1_cast2_fu_634_p1;

assign grp_k2c_dense_1_fu_515_ap_start = grp_k2c_dense_1_fu_515_ap_start_reg;

assign grp_k2c_dense_2_fu_564_ap_start = grp_k2c_dense_2_fu_564_ap_start_reg;

assign grp_k2c_dense_3_fu_540_ap_start = grp_k2c_dense_3_fu_540_ap_start_reg;

assign grp_k2c_dense_fu_588_ap_start = grp_k2c_dense_fu_588_ap_start_reg;

assign tmp_2_fu_811_p2 = ((z2_reg_504 == 4'd10) ? 1'b1 : 1'b0);

assign tmp_fu_639_p2 = ((z1_reg_493 == 10'd784) ? 1'b1 : 1'b0);

assign z1_1_fu_645_p2 = (z1_reg_493 + 10'd1);

assign z1_cast2_fu_634_p1 = z1_reg_493;

assign z2_1_fu_817_p2 = (z2_reg_504 + 4'd1);

assign z2_cast1_fu_806_p1 = z2_reg_504;

always @ (posedge ap_clk) begin
    dense_output_ndim[63:1] <= 63'b000000000000000000000000000000000000000000000000000000000000000;
    dense_output_numel[1:0] <= 2'b00;
    dense_output_numel[4:3] <= 2'b00;
    dense_output_numel[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    dense_1_output_ndim[63:1] <= 63'b000000000000000000000000000000000000000000000000000000000000000;
    dense_1_output_numel[0] <= 1'b0;
    dense_1_output_numel[3:2] <= 2'b00;
    dense_1_output_numel[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    dense_1_kernel_ndim[0] <= 1'b0;
    dense_1_kernel_ndim[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    dense_1_kernel_numel[2:0] <= 3'b000;
    dense_1_kernel_numel[6:4] <= 3'b000;
    dense_1_kernel_numel[11:10] <= 2'b00;
    dense_1_kernel_numel[63:13] <= 51'b000000000000000000000000000000000000000000000000000;
    dense_1_bias_numel[0] <= 1'b0;
    dense_1_bias_numel[3:2] <= 2'b00;
    dense_1_bias_numel[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    dense_2_output_ndim[63:1] <= 63'b000000000000000000000000000000000000000000000000000000000000000;
    dense_2_output_numel[2:1] <= 2'b00;
    dense_2_output_numel[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    dense_2_kernel_ndim[0] <= 1'b0;
    dense_2_kernel_ndim[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    dense_2_kernel_numel[0] <= 1'b0;
    dense_2_kernel_numel[4:2] <= 3'b000;
    dense_2_kernel_numel[9:8] <= 2'b00;
    dense_2_kernel_numel[63:11] <= 53'b00000000000000000000000000000000000000000000000000000;
    dense_2_bias_numel[2:1] <= 2'b00;
    dense_2_bias_numel[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    dense_3_kernel_ndim[0] <= 1'b0;
    dense_3_kernel_ndim[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    dense_3_kernel_numel[0] <= 1'b0;
    dense_3_kernel_numel[2:2] <= 1'b0;
    dense_3_kernel_numel[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    dense_3_bias_numel[0] <= 1'b0;
    dense_3_bias_numel[2:2] <= 1'b0;
    dense_3_bias_numel[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    reg_622[0] <= 1'b0;
    reg_622[3:2] <= 2'b00;
    reg_622[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    reg_628[2:1] <= 2'b00;
    reg_628[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    z1_cast2_reg_823[63:10] <= 54'b000000000000000000000000000000000000000000000000000000;
    z2_cast1_reg_941[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //vlsiModel
