// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_0_0_0_0_0_0_0_HH_
#define _dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_0_0_0_0_0_0_0_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "myproject_mux_255_16_1_1.h"
#include "myproject_mux_104_16_1_1.h"
#include "dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_0_0_0_0_0_0_0_w8_V.h"
#include "dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_0_0_0_0_0_0_0_mult_V.h"

namespace ap_rtl {

struct dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_0_0_0_0_0_0_0 : public sc_module {
    // Port declarations 41
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > p_read;
    sc_in< sc_lv<16> > p_read1;
    sc_in< sc_lv<16> > p_read2;
    sc_in< sc_lv<16> > p_read3;
    sc_in< sc_lv<16> > p_read4;
    sc_in< sc_lv<16> > p_read5;
    sc_in< sc_lv<16> > p_read6;
    sc_in< sc_lv<16> > p_read7;
    sc_in< sc_lv<16> > p_read8;
    sc_in< sc_lv<16> > p_read9;
    sc_in< sc_lv<16> > p_read10;
    sc_in< sc_lv<16> > p_read11;
    sc_in< sc_lv<16> > p_read12;
    sc_in< sc_lv<16> > p_read13;
    sc_in< sc_lv<16> > p_read14;
    sc_in< sc_lv<16> > p_read15;
    sc_in< sc_lv<16> > p_read16;
    sc_in< sc_lv<16> > p_read17;
    sc_in< sc_lv<16> > p_read18;
    sc_in< sc_lv<16> > p_read19;
    sc_in< sc_lv<16> > p_read20;
    sc_in< sc_lv<16> > p_read21;
    sc_in< sc_lv<16> > p_read22;
    sc_in< sc_lv<16> > p_read23;
    sc_in< sc_lv<16> > p_read24;
    sc_out< sc_lv<16> > ap_return_0;
    sc_out< sc_lv<16> > ap_return_1;
    sc_out< sc_lv<16> > ap_return_2;
    sc_out< sc_lv<16> > ap_return_3;
    sc_out< sc_lv<16> > ap_return_4;
    sc_out< sc_lv<16> > ap_return_5;
    sc_out< sc_lv<16> > ap_return_6;
    sc_out< sc_lv<16> > ap_return_7;
    sc_out< sc_lv<16> > ap_return_8;
    sc_out< sc_lv<16> > ap_return_9;
    sc_signal< sc_lv<16> > ap_var_for_const0;
    sc_signal< sc_lv<16> > ap_var_for_const1;
    sc_signal< sc_lv<16> > ap_var_for_const2;
    sc_signal< sc_lv<16> > ap_var_for_const3;
    sc_signal< sc_lv<16> > ap_var_for_const4;
    sc_signal< sc_lv<16> > ap_var_for_const5;
    sc_signal< sc_lv<16> > ap_var_for_const6;
    sc_signal< sc_lv<16> > ap_var_for_const7;
    sc_signal< sc_lv<16> > ap_var_for_const8;
    sc_signal< sc_lv<16> > ap_var_for_const9;


    // Module declarations
    dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_0_0_0_0_0_0_0(sc_module_name name);
    SC_HAS_PROCESS(dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_0_0_0_0_0_0_0);

    ~dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_0_0_0_0_0_0_0();

    sc_trace_file* mVcdFile;

    dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_0_0_0_0_0_0_0_w8_V* w8_V_U;
    dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config8_0_0_0_0_0_0_0_0_0_0_0_mult_V* mult_V_U;
    myproject_mux_255_16_1_1<1,1,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,5,16>* myproject_mux_255_16_1_1_U350;
    myproject_mux_104_16_1_1<1,1,16,16,16,16,16,16,16,16,16,16,4,16>* myproject_mux_104_16_1_1_U351;
    myproject_mux_104_16_1_1<1,1,16,16,16,16,16,16,16,16,16,16,4,16>* myproject_mux_104_16_1_1_U352;
    myproject_mux_104_16_1_1<1,1,16,16,16,16,16,16,16,16,16,16,4,16>* myproject_mux_104_16_1_1_U353;
    sc_signal< sc_lv<12> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<8> > w8_V_address0;
    sc_signal< sc_logic > w8_V_ce0;
    sc_signal< sc_lv<11> > w8_V_q0;
    sc_signal< sc_lv<5> > ii_1_fu_1574_p2;
    sc_signal< sc_lv<5> > ii_1_reg_2300;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<8> > p_shl_fu_1611_p3;
    sc_signal< sc_lv<8> > p_shl_reg_2305;
    sc_signal< sc_lv<1> > tmp_fu_1568_p2;
    sc_signal< sc_lv<6> > p_shl1_fu_1619_p3;
    sc_signal< sc_lv<6> > p_shl1_reg_2310;
    sc_signal< sc_lv<26> > OP1_V_cast_fu_1627_p1;
    sc_signal< sc_lv<26> > OP1_V_cast_reg_2315;
    sc_signal< sc_lv<4> > jj_1_fu_1641_p2;
    sc_signal< sc_lv<4> > jj_1_reg_2383;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<64> > tmp_6_fu_1661_p1;
    sc_signal< sc_lv<64> > tmp_6_reg_2388;
    sc_signal< sc_lv<1> > tmp_3_fu_1635_p2;
    sc_signal< sc_lv<16> > tmp_9_reg_2398;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<4> > iacc_1_fu_1717_p2;
    sc_signal< sc_lv<4> > iacc_1_reg_2406;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<5> > ii_2_fu_1855_p2;
    sc_signal< sc_lv<5> > ii_2_reg_2484;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<8> > p_shl2_fu_1861_p3;
    sc_signal< sc_lv<8> > p_shl2_reg_2489;
    sc_signal< sc_lv<1> > tmp_2_fu_1849_p2;
    sc_signal< sc_lv<6> > p_shl3_fu_1869_p3;
    sc_signal< sc_lv<6> > p_shl3_reg_2494;
    sc_signal< sc_lv<4> > jj_2_fu_1887_p2;
    sc_signal< sc_lv<4> > jj_2_reg_2562;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<1> > tmp_5_fu_1881_p2;
    sc_signal< sc_lv<4> > ires_1_fu_2000_p2;
    sc_signal< sc_lv<4> > ires_1_reg_2575;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<8> > mult_V_address0;
    sc_signal< sc_logic > mult_V_ce0;
    sc_signal< sc_logic > mult_V_we0;
    sc_signal< sc_lv<16> > mult_V_q0;
    sc_signal< sc_lv<5> > ii_reg_464;
    sc_signal< sc_lv<4> > jj_reg_475;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<4> > ap_phi_mux_iacc_phi_fu_490_p4;
    sc_signal< sc_lv<4> > iacc_reg_486;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<5> > ii2_reg_497;
    sc_signal< sc_lv<1> > tmp_s_fu_1711_p2;
    sc_signal< sc_lv<4> > jj3_reg_508;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<4> > ap_phi_mux_ires_phi_fu_524_p4;
    sc_signal< sc_lv<4> > ires_reg_520;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<64> > tmp_10_fu_1907_p1;
    sc_signal< sc_lv<16> > acc_9_V_1_fu_162;
    sc_signal< sc_lv<16> > acc_0_V_fu_1723_p12;
    sc_signal< sc_lv<16> > acc_9_V_3_fu_166;
    sc_signal< sc_lv<16> > acc_9_V_4_fu_170;
    sc_signal< sc_lv<16> > acc_9_V_5_fu_174;
    sc_signal< sc_lv<16> > acc_9_V_6_fu_178;
    sc_signal< sc_lv<16> > acc_9_V_7_fu_182;
    sc_signal< sc_lv<16> > acc_9_V_8_fu_186;
    sc_signal< sc_lv<16> > acc_9_V_9_fu_190;
    sc_signal< sc_lv<16> > acc_9_V_10_fu_194;
    sc_signal< sc_lv<16> > acc_9_V_fu_198;
    sc_signal< sc_lv<16> > acc_9_V_11_fu_202;
    sc_signal< sc_lv<16> > acc_0_V_1_fu_1938_p2;
    sc_signal< sc_lv<1> > tmp_4_fu_1994_p2;
    sc_signal< sc_lv<16> > acc_9_V_12_fu_206;
    sc_signal< sc_lv<16> > acc_9_V_13_fu_210;
    sc_signal< sc_lv<16> > acc_9_V_14_fu_214;
    sc_signal< sc_lv<16> > acc_9_V_15_fu_218;
    sc_signal< sc_lv<16> > acc_9_V_16_fu_222;
    sc_signal< sc_lv<16> > acc_9_V_17_fu_226;
    sc_signal< sc_lv<16> > acc_9_V_18_fu_230;
    sc_signal< sc_lv<16> > acc_9_V_19_fu_234;
    sc_signal< sc_lv<16> > acc_9_V_2_fu_238;
    sc_signal< sc_lv<16> > res_9_V_write_assign_fu_242;
    sc_signal< sc_lv<16> > tmp_37_fu_2006_p12;
    sc_signal< sc_lv<16> > res_8_V_write_assign_fu_246;
    sc_signal< sc_lv<16> > res_0_V_write_assign_fu_250;
    sc_signal< sc_lv<16> > res_7_V_write_assign_fu_254;
    sc_signal< sc_lv<16> > res_6_V_write_assign_fu_258;
    sc_signal< sc_lv<16> > res_1_V_write_assign_fu_262;
    sc_signal< sc_lv<16> > res_5_V_write_assign_fu_266;
    sc_signal< sc_lv<16> > res_4_V_write_assign_fu_270;
    sc_signal< sc_lv<16> > res_2_V_write_assign_fu_274;
    sc_signal< sc_lv<16> > res_3_V_write_assign_fu_278;
    sc_signal< sc_lv<16> > p_Val2_s_fu_680_p0;
    sc_signal< sc_lv<11> > p_Val2_s_fu_680_p1;
    sc_signal< sc_lv<16> > cache_V_fu_1580_p27;
    sc_signal< sc_lv<6> > jj_cast_fu_1631_p1;
    sc_signal< sc_lv<6> > tmp1_fu_1647_p2;
    sc_signal< sc_lv<8> > tmp25_cast_fu_1652_p1;
    sc_signal< sc_lv<8> > index_fu_1656_p2;
    sc_signal< sc_lv<26> > p_Val2_s_fu_680_p2;
    sc_signal< sc_lv<6> > jj3_cast_fu_1877_p1;
    sc_signal< sc_lv<6> > tmp2_fu_1893_p2;
    sc_signal< sc_lv<8> > tmp26_cast_fu_1898_p1;
    sc_signal< sc_lv<8> > index_1_fu_1902_p2;
    sc_signal< sc_lv<16> > p_Val2_37_fu_1912_p12;
    sc_signal< sc_lv<12> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<12> ap_ST_fsm_state1;
    static const sc_lv<12> ap_ST_fsm_state2;
    static const sc_lv<12> ap_ST_fsm_state3;
    static const sc_lv<12> ap_ST_fsm_state4;
    static const sc_lv<12> ap_ST_fsm_state5;
    static const sc_lv<12> ap_ST_fsm_state6;
    static const sc_lv<12> ap_ST_fsm_state7;
    static const sc_lv<12> ap_ST_fsm_state8;
    static const sc_lv<12> ap_ST_fsm_state9;
    static const sc_lv<12> ap_ST_fsm_state10;
    static const sc_lv<12> ap_ST_fsm_state11;
    static const sc_lv<12> ap_ST_fsm_state12;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<4> ap_const_lv4_2;
    static const sc_lv<4> ap_const_lv4_3;
    static const sc_lv<4> ap_const_lv4_4;
    static const sc_lv<4> ap_const_lv4_5;
    static const sc_lv<4> ap_const_lv4_6;
    static const sc_lv<4> ap_const_lv4_7;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<5> ap_const_lv5_19;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<16> ap_const_lv16_FFA2;
    static const sc_lv<16> ap_const_lv16_FFDB;
    static const sc_lv<16> ap_const_lv16_FFEF;
    static const sc_lv<16> ap_const_lv16_FFC9;
    static const sc_lv<16> ap_const_lv16_FFFB;
    static const sc_lv<16> ap_const_lv16_79;
    static const sc_lv<16> ap_const_lv16_FF92;
    static const sc_lv<16> ap_const_lv16_FFEE;
    static const sc_lv<16> ap_const_lv16_4A;
    static const sc_lv<16> ap_const_lv16_13;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const3();
    void thread_ap_var_for_const4();
    void thread_ap_var_for_const5();
    void thread_ap_var_for_const6();
    void thread_ap_var_for_const7();
    void thread_ap_var_for_const8();
    void thread_ap_var_for_const9();
    void thread_ap_clk_no_reset_();
    void thread_OP1_V_cast_fu_1627_p1();
    void thread_acc_0_V_1_fu_1938_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_iacc_phi_fu_490_p4();
    void thread_ap_phi_mux_ires_phi_fu_524_p4();
    void thread_ap_ready();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_return_2();
    void thread_ap_return_3();
    void thread_ap_return_4();
    void thread_ap_return_5();
    void thread_ap_return_6();
    void thread_ap_return_7();
    void thread_ap_return_8();
    void thread_ap_return_9();
    void thread_iacc_1_fu_1717_p2();
    void thread_ii_1_fu_1574_p2();
    void thread_ii_2_fu_1855_p2();
    void thread_index_1_fu_1902_p2();
    void thread_index_fu_1656_p2();
    void thread_ires_1_fu_2000_p2();
    void thread_jj3_cast_fu_1877_p1();
    void thread_jj_1_fu_1641_p2();
    void thread_jj_2_fu_1887_p2();
    void thread_jj_cast_fu_1631_p1();
    void thread_mult_V_address0();
    void thread_mult_V_ce0();
    void thread_mult_V_we0();
    void thread_p_Val2_s_fu_680_p0();
    void thread_p_Val2_s_fu_680_p1();
    void thread_p_Val2_s_fu_680_p2();
    void thread_p_shl1_fu_1619_p3();
    void thread_p_shl2_fu_1861_p3();
    void thread_p_shl3_fu_1869_p3();
    void thread_p_shl_fu_1611_p3();
    void thread_tmp1_fu_1647_p2();
    void thread_tmp25_cast_fu_1652_p1();
    void thread_tmp26_cast_fu_1898_p1();
    void thread_tmp2_fu_1893_p2();
    void thread_tmp_10_fu_1907_p1();
    void thread_tmp_2_fu_1849_p2();
    void thread_tmp_3_fu_1635_p2();
    void thread_tmp_4_fu_1994_p2();
    void thread_tmp_5_fu_1881_p2();
    void thread_tmp_6_fu_1661_p1();
    void thread_tmp_fu_1568_p2();
    void thread_tmp_s_fu_1711_p2();
    void thread_w8_V_address0();
    void thread_w8_V_ce0();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
