Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'hls4ml_model/keras_model.h5'
OutputDir: hls4ml_model
OutputPredictions: null
Part: xc7a200tfbg676-2
ProjectName: myproject
Stamp: C5DC80f5
Version: 1.0.0
