// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _k2c_dense_2_HH_
#define _k2c_dense_2_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "k2c_dot_1.h"
#include "k2c_affine_matmul_1.h"
#include "k2c_relu_func_1.h"
#include "vlsiModel_fadd_32cud.h"
#include "vlsiModel_mul_64sbkb.h"
#include "k2c_dense_2_densezec.h"
#include "k2c_dense_2_denseAem.h"

namespace ap_rtl {

struct k2c_dense_2 : public sc_module {
    // Port declarations 26
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<64> > output_numel_read;
    sc_in< sc_lv<64> > input_ndim_read;
    sc_in< sc_lv<64> > input_numel_read;
    sc_out< sc_lv<3> > input_shape_address0;
    sc_out< sc_logic > input_shape_ce0;
    sc_in< sc_lv<64> > input_shape_q0;
    sc_in< sc_lv<64> > kernel_ndim_read;
    sc_in< sc_lv<64> > kernel_numel_read;
    sc_out< sc_lv<3> > kernel_shape_address0;
    sc_out< sc_logic > kernel_shape_ce0;
    sc_in< sc_lv<64> > kernel_shape_q0;
    sc_in< sc_lv<64> > bias_numel_read;
    sc_out< sc_lv<5> > dense_2_output_array_address0;
    sc_out< sc_logic > dense_2_output_array_ce0;
    sc_out< sc_logic > dense_2_output_array_we0;
    sc_out< sc_lv<32> > dense_2_output_array_d0;
    sc_in< sc_lv<32> > dense_2_output_array_q0;
    sc_out< sc_lv<6> > dense_1_output_array_address0;
    sc_out< sc_logic > dense_1_output_array_ce0;
    sc_in< sc_lv<32> > dense_1_output_array_q0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    k2c_dense_2(sc_module_name name);
    SC_HAS_PROCESS(k2c_dense_2);

    ~k2c_dense_2();

    sc_trace_file* mVcdFile;

    k2c_dense_2_densezec* dense_2_kernel_array_U;
    k2c_dense_2_denseAem* dense_2_bias_array_U;
    k2c_dot_1* grp_k2c_dot_1_fu_172;
    k2c_affine_matmul_1* grp_k2c_affine_matmul_1_fu_197;
    k2c_relu_func_1* grp_k2c_relu_func_1_fu_213;
    vlsiModel_fadd_32cud<1,5,32,32,32>* vlsiModel_fadd_32cud_U170;
    vlsiModel_mul_64sbkb<1,2,64,64,64>* vlsiModel_mul_64sbkb_U171;
    sc_signal< sc_lv<16> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<11> > dense_2_kernel_array_address0;
    sc_signal< sc_logic > dense_2_kernel_array_ce0;
    sc_signal< sc_lv<32> > dense_2_kernel_array_q0;
    sc_signal< sc_lv<5> > dense_2_bias_array_address0;
    sc_signal< sc_logic > dense_2_bias_array_ce0;
    sc_signal< sc_lv<32> > dense_2_bias_array_q0;
    sc_signal< sc_lv<1> > tmp_fu_226_p2;
    sc_signal< sc_lv<1> > tmp_reg_338;
    sc_signal< sc_lv<64> > tmp_6_fu_232_p2;
    sc_signal< sc_lv<64> > tmp_6_reg_342;
    sc_signal< sc_lv<1> > icmp_fu_249_p2;
    sc_signal< sc_lv<1> > icmp_reg_347;
    sc_signal< sc_lv<64> > j_fu_269_p2;
    sc_signal< sc_lv<64> > j_reg_368;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > exitcond_i_fu_264_p2;
    sc_signal< sc_lv<5> > dense_2_output_array_1_reg_378;
    sc_signal< sc_lv<64> > i_fu_290_p2;
    sc_signal< sc_lv<32> > dense_2_bias_array_l_reg_388;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<64> > outrows1_fu_295_p3;
    sc_signal< sc_lv<64> > outrows1_reg_398;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<64> > outcols_reg_404;
    sc_signal< sc_lv<64> > innerdim_reg_415;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<64> > grp_fu_302_p2;
    sc_signal< sc_lv<64> > outsize_reg_420;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_logic > grp_k2c_affine_matmul_1_fu_197_ap_idle;
    sc_signal< sc_logic > grp_k2c_affine_matmul_1_fu_197_ap_ready;
    sc_signal< sc_logic > grp_k2c_affine_matmul_1_fu_197_ap_done;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_172_ap_start;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_172_ap_done;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_172_ap_idle;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_172_ap_ready;
    sc_signal< sc_lv<3> > grp_k2c_dot_1_fu_172_A_shape_address0;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_172_A_shape_ce0;
    sc_signal< sc_lv<3> > grp_k2c_dot_1_fu_172_B_shape_address0;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_172_B_shape_ce0;
    sc_signal< sc_lv<5> > grp_k2c_dot_1_fu_172_C_array_address0;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_172_C_array_ce0;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_172_C_array_we0;
    sc_signal< sc_lv<32> > grp_k2c_dot_1_fu_172_C_array_d0;
    sc_signal< sc_lv<6> > grp_k2c_dot_1_fu_172_A_array_address0;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_172_A_array_ce0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_1_fu_197_ap_start;
    sc_signal< sc_lv<5> > grp_k2c_affine_matmul_1_fu_197_C_address0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_1_fu_197_C_ce0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_1_fu_197_C_we0;
    sc_signal< sc_lv<32> > grp_k2c_affine_matmul_1_fu_197_C_d0;
    sc_signal< sc_lv<6> > grp_k2c_affine_matmul_1_fu_197_A_address0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_1_fu_197_A_ce0;
    sc_signal< sc_lv<11> > grp_k2c_affine_matmul_1_fu_197_B_address0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_1_fu_197_B_ce0;
    sc_signal< sc_lv<5> > grp_k2c_affine_matmul_1_fu_197_d_address0;
    sc_signal< sc_logic > grp_k2c_affine_matmul_1_fu_197_d_ce0;
    sc_signal< sc_logic > grp_k2c_relu_func_1_fu_213_ap_start;
    sc_signal< sc_logic > grp_k2c_relu_func_1_fu_213_ap_done;
    sc_signal< sc_logic > grp_k2c_relu_func_1_fu_213_ap_idle;
    sc_signal< sc_logic > grp_k2c_relu_func_1_fu_213_ap_ready;
    sc_signal< sc_lv<5> > grp_k2c_relu_func_1_fu_213_x_address0;
    sc_signal< sc_logic > grp_k2c_relu_func_1_fu_213_x_ce0;
    sc_signal< sc_logic > grp_k2c_relu_func_1_fu_213_x_we0;
    sc_signal< sc_lv<32> > grp_k2c_relu_func_1_fu_213_x_d0;
    sc_signal< sc_lv<64> > grp_k2c_relu_func_1_fu_213_size;
    sc_signal< sc_lv<64> > i_i_reg_148;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<64> > j_i_reg_160;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > tmp_i_fu_255_p2;
    sc_signal< sc_logic > grp_k2c_dot_1_fu_172_ap_start_reg;
    sc_signal< sc_logic > grp_k2c_affine_matmul_1_fu_197_ap_start_reg;
    sc_signal< sc_logic > grp_k2c_relu_func_1_fu_213_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<64> > sum_i_cast_fu_285_p1;
    sc_signal< sc_lv<32> > grp_fu_220_p2;
    sc_signal< sc_lv<63> > tmp_87_fu_239_p4;
    sc_signal< sc_lv<6> > tmp_89_fu_275_p1;
    sc_signal< sc_lv<6> > tmp_88_fu_260_p1;
    sc_signal< sc_lv<6> > sum_i_fu_279_p2;
    sc_signal< sc_logic > grp_fu_302_ce;
    sc_signal< bool > ap_block_state16_on_subcall_done;
    sc_signal< sc_lv<16> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<16> ap_ST_fsm_state1;
    static const sc_lv<16> ap_ST_fsm_state2;
    static const sc_lv<16> ap_ST_fsm_state3;
    static const sc_lv<16> ap_ST_fsm_state4;
    static const sc_lv<16> ap_ST_fsm_state5;
    static const sc_lv<16> ap_ST_fsm_state6;
    static const sc_lv<16> ap_ST_fsm_state7;
    static const sc_lv<16> ap_ST_fsm_state8;
    static const sc_lv<16> ap_ST_fsm_state9;
    static const sc_lv<16> ap_ST_fsm_state10;
    static const sc_lv<16> ap_ST_fsm_state11;
    static const sc_lv<16> ap_ST_fsm_state12;
    static const sc_lv<16> ap_ST_fsm_state13;
    static const sc_lv<16> ap_ST_fsm_state14;
    static const sc_lv<16> ap_ST_fsm_state15;
    static const sc_lv<16> ap_ST_fsm_state16;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<64> ap_const_lv64_3;
    static const sc_lv<64> ap_const_lv64_FFFFFFFFFFFFFFFF;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<63> ap_const_lv63_0;
    static const bool ap_const_boolean_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_block_state16_on_subcall_done();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_dense_1_output_array_address0();
    void thread_dense_1_output_array_ce0();
    void thread_dense_2_bias_array_address0();
    void thread_dense_2_bias_array_ce0();
    void thread_dense_2_kernel_array_address0();
    void thread_dense_2_kernel_array_ce0();
    void thread_dense_2_output_array_address0();
    void thread_dense_2_output_array_ce0();
    void thread_dense_2_output_array_d0();
    void thread_dense_2_output_array_we0();
    void thread_exitcond_i_fu_264_p2();
    void thread_grp_fu_302_ce();
    void thread_grp_k2c_affine_matmul_1_fu_197_ap_start();
    void thread_grp_k2c_dot_1_fu_172_ap_start();
    void thread_grp_k2c_relu_func_1_fu_213_ap_start();
    void thread_grp_k2c_relu_func_1_fu_213_size();
    void thread_i_fu_290_p2();
    void thread_icmp_fu_249_p2();
    void thread_input_shape_address0();
    void thread_input_shape_ce0();
    void thread_j_fu_269_p2();
    void thread_kernel_shape_address0();
    void thread_kernel_shape_ce0();
    void thread_outrows1_fu_295_p3();
    void thread_sum_i_cast_fu_285_p1();
    void thread_sum_i_fu_279_p2();
    void thread_tmp_6_fu_232_p2();
    void thread_tmp_87_fu_239_p4();
    void thread_tmp_88_fu_260_p1();
    void thread_tmp_89_fu_275_p1();
    void thread_tmp_fu_226_p2();
    void thread_tmp_i_fu_255_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
